In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

IMPORTING DATA FROM YFINANCE

In [2]:
data0=yf.Ticker("AAPL")
data0

yfinance.Ticker object <AAPL>

In [3]:
data0.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allows customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 150000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Senior VP of Government Affairs & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 55,
   'title': 'Senior VP & General Counsel',
   'yearBorn': 1970,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1785542400,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 305.26,
 'open': 306.028,
 'dayLow': 304.31,
 'dayHigh': 307.49,
 'regularMarketPreviousClose': 305.26,
 'regularMarketOpen': 306.028,
 'regularMarketDayLow': 304.3,
 'regularMarketDayHigh': 307.49,
 'dividendRate': 1.08,
 'dividendYield': 0.35,
 'exDividendDate': 1786320000,
 'payoutRatio': 0.1204,
 'fiveYearAvgDividendYield': 0.5,
 'beta': 1.086,
 'trailingPE': 35.083714,
 'forwardPE': 32.17704,
 'volume': 26072932,
 'regularMarketVolume': 26072932,
 'averageVolume': 56191185,
 'averageVolume10days': 46555190,
 'averageDailyVolume10Day': 46555190,
 'bid': 305.02,
 'ask': 306.97,
 'bidSize': 3,
 'askSize': 4,
 'marketCap': 4464797286400,
 'nonDilutedMarketCap': 4449911423800,
 'fiftyTwoWeekLow': 223.78,
 'fiftyTwoWeekHigh': 344.57,
 'allTimeHigh': 344.57,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 9.5642185,
 'fiftyDayAverage': 309.1908,
 'twoHundredDayAverage': 280.48364,
 'trailingAnnualDividendRate': 1.05,
 'trailingAnnualDividendYield': 0.0034396905,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 4486742409216,
 'profitMargins': 0.27618998,
 'floatShares': 14557694550,
 'sharesOutstanding': 14594180000,
 'sharesShort': 141606163,
 'sharesShortPriorMonth': 140526320,
 'sharesShortPreviousMonthDate': 1782777600,
 'dateShortInterest': 1785456000,
 'sharesPercentSharesOut': 0.0097,
 'heldPercentInsiders': 0.01648,
 'heldPercentInstitutions': 0.66483,
 'shortRatio': 2.58,
 'shortPercentOfFloat': 0.0097,
 'impliedSharesOutstanding': 14594180000,
 'bookValue': 7.36,
 'priceToBook': 41.566574,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1782518400,
 'earningsQuarterlyGrowth': 0.271,
 'netIncomeToCommon': 128929996800,
 'trailingEps': 8.72,
 'forwardEps': 9.50771,
 'pegRatio': 2.44,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 9.611,
 'enterpriseToEbitda': 26.713,
 '52WeekChange': 0.32500327,
 'SandP52WeekChange': 0.2072537,
 'lastDividendValue': 0.27,
 'lastDividendDate': 1786320000,
 'quoteType': 'EQUITY',
 'currentPrice': 305.93,
 'targetHighPrice': 400.0,
 'targetLowPrice': 215.0,
 'targetMeanPrice': 322.2844,
 'targetMedianPrice': 335.0,
 'recommendationMean': 2.13043,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 41,
 'totalCash': 62399000576,
 'totalCashPerShare': 4.276,
 'ebitda': 167959003136,
 'totalDebt': 84343996416,
 'quickRatio': 0.812,
 'currentRatio': 1.003,
 'totalRevenue': 466822987776,
 'debtToEquity': 78.445,
 'revenuePerShare': 31.707,
 'returnOnAssets': 0.27082002,
 'returnOnEquity': 1.4875101,
 'grossProfits': 227123003392,
 'freeCashflow': 107721875456,
 'operatingCashflow': 146723995648,
 'earningsGrowth': 0.287,
 'revenueGrowth': 0.164,
 'grossMargins': 0.48653,
 'ebitdaMargins': 0.35979,
 'operatingMargins': 0.32623002,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'CLOSED',
 'cryptoTradeable': False,
 'shortName': 'Apple Inc.',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'postMarketChangePercent': -0.052131165,
 'postMarketPrice': 305.7705,
 'postMarketChange': -0.15948486,
 'regularMarketChange': 0.669983,
 'regularMarketDayRange': '304.3 - 307.49',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 56191185,
 'fiftyTwoWeekLowChange': 82.149994,
 'fiftyTwoWeekLowChangePercent': 0.36710158,
 'fiftyTwoWeekRange': '223.78 - 344.57',
 'fiftyTwoWeekHighChange': -38.640015,
 'fiftyTwoWeekHighChangePercent': -0.112139806,
 'fiftyTwoWeekChangePercent': 32.500328,
 'dividendDate': 1786579200,
 'earningsTimestamp': 1785441600,
 'longName': 'Apple Inc.',
 'earningsTimestampStart': 1793304000,
 'earningsTimestampEnd': 1793304000,
 'earningsCallTimestampStart': 1785441600,
 'earningsCallTimestampEnd': 1785441600,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 8.72,
 'epsForward': 9.50771,
 'epsCurrentYear': 8.7999,
 'priceEpsCurrentYear': 34.765167,
 'fiftyDayAverageChange': -3.2608032,
 'fiftyDayAverageChangePercent': -0.010546249,
 'twoHundredDayAverageChange': 25.44635,
 'twoHundredDayAverageChangePercent': 0.09072312,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.1 - Buy',
 'corporateActions': [],
 'postMarketTime': 1786751999,
 'regularMarketTime': 1786737601,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 0.219479,
 'regularMarketPrice': 305.93,
 'displayName': 'Apple',
 'trailingPegRatio': 2.4856}

In [4]:
df=data0.history(period="1y")

In [5]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.00,0.0
2025-08-18 00:00:00-04:00,230.847254,232.262026,229.263109,230.040237,37476200,0.00,0.0
2025-08-19 00:00:00-04:00,230.428808,232.012952,228.505918,229.711456,39402600,0.00,0.0
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.00,0.0
2025-08-21 00:00:00-04:00,225.437249,225.686329,222.956408,224.072281,30621200,0.00,0.0
...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0

In [6]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 251 entries, 2025-08-15 00:00:00-04:00 to 2026-08-14 00:00:00-04:00
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          251 non-null    float64
 1   High          251 non-null    float64
 2   Low           251 non-null    float64
 3   Close         251 non-null    float64
 4   Volume        251 non-null    int64
 5   Dividends     251 non-null    float64
 6   Stock Splits  251 non-null    float64
dtypes: float64(6), int64(1)
memory usage: 15.7 KB

In [7]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.00,0.0
2025-08-18 00:00:00-04:00,230.847254,232.262026,229.263109,230.040237,37476200,0.00,0.0
2025-08-19 00:00:00-04:00,230.428808,232.012952,228.505918,229.711456,39402600,0.00,0.0
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.00,0.0
2025-08-21 00:00:00-04:00,225.437249,225.686329,222.956408,224.072281,30621200,0.00,0.0
...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0

In [8]:
##FINDING DATES WHERE DIVIDENDS WERE PAID
df[df["Dividends"]!=0]

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-11-10 00:00:00-05:00,268.229883,272.986954,266.733955,268.698608,41312400,0.26,0.0
2026-02-09 00:00:00-05:00,277.414946,277.704438,271.216017,274.130798,44623400,0.26,0.0
2026-05-11 00:00:00-04:00,291.728417,293.626774,289.979925,292.427795,42247300,0.27,0.0
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0

In [9]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 251 entries, 2025-08-15 00:00:00-04:00 to 2026-08-14 00:00:00-04:00
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          251 non-null    float64
 1   High          251 non-null    float64
 2   Low           251 non-null    float64
 3   Close         251 non-null    float64
 4   Volume        251 non-null    int64
 5   Dividends     251 non-null    float64
 6   Stock Splits  251 non-null    float64
dtypes: float64(6), int64(1)
memory usage: 15.7 KB

In [10]:
#how many trading days are there in the data
print(df.shape[0])

251

In [11]:
#average
print("average vol=",np.mean(df['Volume']))

average vol= 49763979.6812749

In [12]:
#date which had the highest volume
df[df["Volume"]==df["Volume"].max()]

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-06-26 00:00:00-04:00,274.763028,285.703605,273.973701,283.535461,261775500,0.0,0.0

In [13]:
df["Volume"].max()

np.int64(261775500)

In [14]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits'], dtype='str')

In [15]:
#day with the highest price
display("highest priced:",df[df['High']==df["High"].max()])
display("lowest priced:",df[df["Low"]==df["Low"].min()])

'highest priced:'

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-07-29 00:00:00-04:00,339.437272,344.273097,337.059318,337.89859,56090800,0.0,0.0

'lowest priced:'

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-08-21 00:00:00-04:00,225.437249,225.686329,222.956408,224.072281,30621200,0.0,0.0

In [16]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.00,0.0
2025-08-18 00:00:00-04:00,230.847254,232.262026,229.263109,230.040237,37476200,0.00,0.0
2025-08-19 00:00:00-04:00,230.428808,232.012952,228.505918,229.711456,39402600,0.00,0.0
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.00,0.0
2025-08-21 00:00:00-04:00,225.437249,225.686329,222.956408,224.072281,30621200,0.00,0.0
...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0

In [17]:

len(df[df["Dividends"]!=0])

4

In [18]:
df["Dividends"].sum()

np.float64(1.06)

In [19]:
df["diff_highlow"]=df.High-df.Low
df[df["diff_highlow"]==df.diff_highlow.max()]

,Open,High,Low,Close,Volume,Dividends,Stock Splits,diff_highlow
Date,,,,,,,,
2026-06-08 00:00:00-04:00,308.47396,317.126501,300.910506,301.280182,77949100,0.0,0.0,16.215996

In [20]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,diff_highlow
Date,,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.00,0.0,4.921821
2025-08-18 00:00:00-04:00,230.847254,232.262026,229.263109,230.040237,37476200,0.00,0.0,2.998917
2025-08-19 00:00:00-04:00,230.428808,232.012952,228.505918,229.711456,39402600,0.00,0.0,3.507034
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.00,0.0,4.682699
2025-08-21 00:00:00-04:00,225.437249,225.686329,222.956408,224.072281,30621200,0.00,0.0,2.729921
...,...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0,3.650024
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0,7.179993
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0,5.089996
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0,3.950012
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0,3.190002

In [21]:
df.rename(columns={"diff_highlow":"Daily Range"},inplace=True)
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Daily Range
Date,,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.00,0.0,4.921821
2025-08-18 00:00:00-04:00,230.847254,232.262026,229.263109,230.040237,37476200,0.00,0.0,2.998917
2025-08-19 00:00:00-04:00,230.428808,232.012952,228.505918,229.711456,39402600,0.00,0.0,3.507034
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.00,0.0,4.682699
2025-08-21 00:00:00-04:00,225.437249,225.686329,222.956408,224.072281,30621200,0.00,0.0,2.729921
...,...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0,3.650024
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0,7.179993
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0,5.089996
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0,3.950012
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0,3.190002

In [22]:
df["Intraday Change"]=df["Close"]-df["Open"]

In [23]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Daily Range,Intraday Change
Date,,,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.00,0.0,4.921821,-2.401134
2025-08-18 00:00:00-04:00,230.847254,232.262026,229.263109,230.040237,37476200,0.00,0.0,2.998917,-0.807016
2025-08-19 00:00:00-04:00,230.428808,232.012952,228.505918,229.711456,39402600,0.00,0.0,3.507034,-0.717351
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.00,0.0,4.682699,-3.955390
2025-08-21 00:00:00-04:00,225.437249,225.686329,222.956408,224.072281,30621200,0.00,0.0,2.729921,-1.364968
...,...,...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0,3.650024,1.430023
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0,7.179993,-2.839996
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0,5.089996,-2.850006
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0,3.950012,1.050018
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0,3.190002,-0.070007

In [24]:
display("Stock closed higher on these days:",df[df["Intraday Change"]>0])
display("Stock closed lower on these days:",df[df["Intraday Change"]<0])

'Stock closed higher on these days:'

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Daily Range,Intraday Change
Date,,,,,,,,,
2025-08-22 00:00:00-04:00,225.337608,228.246860,224.580411,226.921753,42477800,0.00,0.0,3.666449,1.584145
2025-08-25 00:00:00-04:00,225.646469,228.456098,225.397389,226.323975,30983100,0.00,0.0,3.058709,0.677505
2025-08-26 00:00:00-04:00,226.035012,228.645379,223.863042,228.466034,54575100,0.00,0.0,4.782337,2.431022
2025-08-27 00:00:00-04:00,227.768623,230.050188,227.419905,229.641708,31259500,0.00,0.0,2.630283,1.873086
2025-08-28 00:00:00-04:00,229.970500,232.550964,228.495936,231.704086,38074700,0.00,0.0,4.055028,1.733586
...,...,...,...,...,...,...,...,...,...
2026-08-04 00:00:00-04:00,302.469140,310.152516,301.060351,309.113403,68001000,0.00,0.0,9.092164,6.644263
2026-08-05 00:00:00-04:00,309.093424,311.441405,305.406631,310.732025,49438800,0.00,0.0,6.034774,1.638602
2026-08-07 00:00:00-04:00,311.181643,314.538733,310.472233,313.059998,34437200,0.00,0.0,4.066500,1.878354
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0,3.650024,1.430023
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0,3.950012,1.050018

'Stock closed lower on these days:'

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Daily Range,Intraday Change
Date,,,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.0,0.0,4.921821,-2.401134
2025-08-18 00:00:00-04:00,230.847254,232.262026,229.263109,230.040237,37476200,0.0,0.0,2.998917,-0.807016
2025-08-19 00:00:00-04:00,230.428808,232.012952,228.505918,229.711456,39402600,0.0,0.0,3.507034,-0.717351
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.0,0.0,4.682699,-3.955390
2025-08-21 00:00:00-04:00,225.437249,225.686329,222.956408,224.072281,30621200,0.0,0.0,2.729921,-1.364968
...,...,...,...,...,...,...,...,...,...
2026-08-03 00:00:00-04:00,309.313235,311.531323,302.299295,303.158569,75052000,0.0,0.0,9.232029,-6.154665
2026-08-06 00:00:00-04:00,314.069138,316.017470,308.963556,312.140808,46139900,0.0,0.0,7.053914,-1.928330
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.0,0.0,7.179993,-2.839996
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.0,0.0,5.089996,-2.850006
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.0,0.0,3.190002,-0.070007

In [25]:
display("Percentage of green days=",(((df["Intraday Change"]>0).sum())/(len(df)))*100)

'Percentage of green days='

np.float64(54.581673306772906)

In [26]:
df[df["Volume"]>df.Volume.mean()]

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Daily Range,Intraday Change
Date,,,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.0,0.0,4.921821,-2.401134
2025-08-26 00:00:00-04:00,226.035012,228.645379,223.863042,228.466034,54575100,0.0,0.0,4.782337,2.431022
2025-09-03 00:00:00-04:00,236.336989,237.970953,233.497472,237.592346,66427800,0.0,0.0,4.473481,1.255357
2025-09-05 00:00:00-04:00,239.116703,240.431852,237.612266,238.807846,54870400,0.0,0.0,2.819586,-0.308857
2025-09-09 00:00:00-04:00,236.127759,237.901207,232.501156,233.487518,66313900,0.0,0.0,5.400051,-2.640241
...,...,...,...,...,...,...,...,...,...
2026-07-29 00:00:00-04:00,339.437272,344.273097,337.059318,337.898590,56090800,0.0,0.0,7.213780,-1.538682
2026-07-30 00:00:00-04:00,332.812967,334.461540,329.305982,333.142670,74817800,0.0,0.0,5.155557,0.329702
2026-07-31 00:00:00-04:00,304.547356,310.422294,299.741503,308.643829,132489100,0.0,0.0,10.680791,4.096473
2026-08-03 00:00:00-04:00,309.313235,311.531323,302.299295,303.158569,75052000,0.0,0.0,9.232029,-6.154665
2026-08-04 00:00:00-04:00,302.469140,310.152516,301.060351,309.113403,68001000,0.0,0.0,9.092164,6.644263

In [27]:
df.sort_values(by=["Close"],ascending=0)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Daily Range,Intraday Change
Date,,,,,,,,,
2026-07-28 00:00:00-04:00,339.736982,342.594533,335.310806,339.786926,51859000,0.0,0.0,7.283726,0.049945
2026-07-29 00:00:00-04:00,339.437272,344.273097,337.059318,337.898590,56090800,0.0,0.0,7.213780,-1.538682
2026-07-27 00:00:00-04:00,334.251737,339.277401,333.732166,336.619690,49604300,0.0,0.0,5.545236,2.367953
2026-07-17 00:00:00-04:00,331.693930,334.701315,328.716487,333.452393,63407100,0.0,0.0,5.984828,1.758463
2026-07-30 00:00:00-04:00,332.812967,334.461540,329.305982,333.142670,74817800,0.0,0.0,5.155557,0.329702
...,...,...,...,...,...,...,...,...,...
2025-08-22 00:00:00-04:00,225.337608,228.246860,224.580411,226.921753,42477800,0.0,0.0,3.666449,1.584145
2025-08-25 00:00:00-04:00,225.646469,228.456098,225.397389,226.323975,30983100,0.0,0.0,3.058709,0.677505
2025-09-10 00:00:00-04:00,231.335473,231.564622,225.118433,225.955338,83440800,0.0,0.0,6.446190,-5.380135
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.0,0.0,4.682699,-3.955390
2025-08-21 00:00:00-04:00,225.437249,225.686329,222.956408,224.072281,30621200,0.0,0.0,2.729921,-1.364968

In [28]:
df.sort_values(by="Volume",ascending=0,inplace=True)
df.head(10)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Daily Range,Intraday Change
Date,,,,,,,,,
2026-06-26 00:00:00-04:00,274.763028,285.703605,273.973701,283.535461,261775500,0.0,0.0,11.729904,8.772433
2025-09-19 00:00:00-04:00,240.342162,245.393509,239.325927,244.596451,163741300,0.0,0.0,6.067582,4.254289
2025-12-19 00:00:00-05:00,271.411231,273.854592,269.167338,272.927124,144632000,0.0,0.0,4.687254,1.515893
2026-07-31 00:00:00-04:00,304.547356,310.422294,299.741503,308.643829,132489100,0.0,0.0,10.680791,4.096473
2026-06-25 00:00:00-04:00,287.152347,288.551135,273.514115,274.912903,107013700,0.0,0.0,15.037020,-12.239444
2025-09-22 00:00:00-04:00,247.386162,255.695479,247.206817,255.137512,105517400,0.0,0.0,8.488663,7.751350
2026-01-30 00:00:00-05:00,254.477322,261.189048,251.495433,258.775635,92443400,0.0,0.0,9.693616,4.298313
2026-04-30 00:00:00-04:00,270.018146,275.508349,267.662365,270.866638,91848200,0.0,0.0,7.845984,0.848492
2026-02-04 00:00:00-05:00,271.550860,278.192785,271.550860,275.739441,90545700,0.0,0.0,6.641925,4.188581
2025-10-20 00:00:00-04:00,254.948221,263.406980,254.689183,261.274841,90483000,0.0,0.0,8.717796,6.326620

In [29]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Daily Range,Intraday Change
Date,,,,,,,,,
2026-06-26 00:00:00-04:00,274.763028,285.703605,273.973701,283.535461,261775500,0.0,0.0,11.729904,8.772433
2025-09-19 00:00:00-04:00,240.342162,245.393509,239.325927,244.596451,163741300,0.0,0.0,6.067582,4.254289
2025-12-19 00:00:00-05:00,271.411231,273.854592,269.167338,272.927124,144632000,0.0,0.0,4.687254,1.515893
2026-07-31 00:00:00-04:00,304.547356,310.422294,299.741503,308.643829,132489100,0.0,0.0,10.680791,4.096473
2026-06-25 00:00:00-04:00,287.152347,288.551135,273.514115,274.912903,107013700,0.0,0.0,15.037020,-12.239444
...,...,...,...,...,...,...,...,...,...
2025-12-29 00:00:00-05:00,271.949773,273.615223,271.610700,273.016876,23715200,0.0,0.0,2.004523,1.067103
2025-12-30 00:00:00-05:00,272.069428,273.335969,271.540868,272.338684,22139600,0.0,0.0,1.795102,0.269256
2025-12-26 00:00:00-05:00,273.415753,274.622460,272.119264,272.657806,21521800,0.0,0.0,2.503196,-0.757947
2025-11-28 00:00:00-05:00,276.507338,278.242604,275.240766,278.093018,20135600,0.0,0.0,3.001839,1.585680
2025-12-24 00:00:00-05:00,271.600731,274.682340,271.461127,273.066742,17910600,0.0,0.0,3.221213,1.466011

In [30]:
ticker=yf.Ticker("AAPL")
ticker
df=ticker.history(period="1y")

In [31]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.00,0.0
2025-08-18 00:00:00-04:00,230.847254,232.262026,229.263109,230.040237,37476200,0.00,0.0
2025-08-19 00:00:00-04:00,230.428808,232.012952,228.505918,229.711456,39402600,0.00,0.0
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.00,0.0
2025-08-21 00:00:00-04:00,225.437249,225.686329,222.956408,224.072281,30621200,0.00,0.0
...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0

In [32]:
top10=df.nlargest(10,"Volume")
top10

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-06-26 00:00:00-04:00,274.763028,285.703605,273.973701,283.535461,261775500,0.0,0.0
2025-09-19 00:00:00-04:00,240.342162,245.393509,239.325927,244.596451,163741300,0.0,0.0
2025-12-19 00:00:00-05:00,271.411231,273.854592,269.167338,272.927124,144632000,0.0,0.0
2026-07-31 00:00:00-04:00,304.547356,310.422294,299.741503,308.643829,132489100,0.0,0.0
2026-06-25 00:00:00-04:00,287.152347,288.551135,273.514115,274.912903,107013700,0.0,0.0
2025-09-22 00:00:00-04:00,247.386162,255.695479,247.206817,255.137512,105517400,0.0,0.0
2026-01-30 00:00:00-05:00,254.477322,261.189048,251.495433,258.775635,92443400,0.0,0.0
2026-04-30 00:00:00-04:00,270.018146,275.508349,267.662365,270.866638,91848200,0.0,0.0
2026-02-04 00:00:00-05:00,271.550860,278.192785,271.550860,275.739441,90545700,0.0,0.0
2025-10-20 00:00:00-04:00,254.948221,263.406980,254.689183,261.274841,90483000,0.0,0.0

In [33]:
df.head(10)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.0,0.0
2025-08-18 00:00:00-04:00,230.847254,232.262026,229.263109,230.040237,37476200,0.0,0.0
2025-08-19 00:00:00-04:00,230.428808,232.012952,228.505918,229.711456,39402600,0.0,0.0
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.0,0.0
2025-08-21 00:00:00-04:00,225.437249,225.686329,222.956408,224.072281,30621200,0.0,0.0
2025-08-22 00:00:00-04:00,225.337608,228.246860,224.580411,226.921753,42477800,0.0,0.0
2025-08-25 00:00:00-04:00,225.646469,228.456098,225.397389,226.323975,30983100,0.0,0.0
2025-08-26 00:00:00-04:00,226.035012,228.645379,223.863042,228.466034,54575100,0.0,0.0
2025-08-27 00:00:00-04:00,227.768623,230.050188,227.419905,229.641708,31259500,0.0,0.0
2025-08-28 00:00:00-04:00,229.970500,232.550964,228.495936,231.704086,38074700,0.0,0.0

In [34]:
df.head(25)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.0,0.0
2025-08-18 00:00:00-04:00,230.847254,232.262026,229.263109,230.040237,37476200,0.0,0.0
2025-08-19 00:00:00-04:00,230.428808,232.012952,228.505918,229.711456,39402600,0.0,0.0
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.0,0.0
2025-08-21 00:00:00-04:00,225.437249,225.686329,222.956408,224.072281,30621200,0.0,0.0
2025-08-22 00:00:00-04:00,225.337608,228.246860,224.580411,226.921753,42477800,0.0,0.0
2025-08-25 00:00:00-04:00,225.646469,228.456098,225.397389,226.323975,30983100,0.0,0.0
2025-08-26 00:00:00-04:00,226.035012,228.645379,223.863042,228.466034,54575100,0.0,0.0
2025-08-27 00:00:00-04:00,227.768623,230.050188,227.419905,229.641708,31259500,0.0,0.0
2025-08-28 00:00:00-04:00,229.970500,232.550964,228.495936,231.704086,38074700,0.0,0.0
2025-08-29 00:00:00-04:00,231.654263,232.521071,230.518459,231.285629,39418400,0.0,0.0
2025-09-02 00:00:00-04:00,228.406271,230.000388,226.134663,228.874542,44075600,0.0,0.0
2025-09-03 00:00:00-04:00,236.336989,237.970953,233.497472,237.592346,66427800,0.0,0.0
2025-09-04 00:00:00-04:00,237.572400,239.017060,235.868702,238.897507,47549400,0.0,0.0
2025-09-05 00:00:00-04:00,239.116703,240.431852,237.612266,238.807846,54870400,0.0,0.0
2025-09-08 00:00:00-04:00,238.419289,239.266151,235.470176,237.004517,48999500,0.0,0.0
2025-09-09 00:00:00-04:00,236.127759,237.901207,232.501156,233.487518,66313900,0.0,0.0
2025-09-10 00:00:00-04:00,231.335473,231.564622,225.118433,225.955338,83440800,0.0,0.0
2025-09-11 00:00:00-04:00,226.045010,229.601863,225.815845,229.183411,50208600,0.0,0.0
2025-09-12 00:00:00-04:00,228.376386,233.646910,228.177125,233.208542,55824200,0.0,0.0
2025-09-15 00:00:00-04:00,236.127756,237.313379,234.165005,235.828857,42699500,0.0,0.0
2025-09-16 00:00:00-04:00,236.307067,240.332207,235.450247,237.273499,63421100,0.0,0.0
2025-09-17 00:00:00-04:00,238.090512,239.216359,236.855071,238.110443,46508000,0.0,0.0
2025-09-18 00:00:00-04:00,239.086821,240.312290,235.779033,237.004517,44249600,0.0,0.0
2025-09-19 00:00:00-04:00,240.342162,245.393509,239.325927,244.596451,163741300,0.0,0.0

In [35]:
df.index

DatetimeIndex(['2025-08-15 00:00:00-04:00', '2025-08-18 00:00:00-04:00',
               '2025-08-19 00:00:00-04:00', '2025-08-20 00:00:00-04:00',
               '2025-08-21 00:00:00-04:00', '2025-08-22 00:00:00-04:00',
               '2025-08-25 00:00:00-04:00', '2025-08-26 00:00:00-04:00',
               '2025-08-27 00:00:00-04:00', '2025-08-28 00:00:00-04:00',
               ...
               '2026-08-03 00:00:00-04:00', '2026-08-04 00:00:00-04:00',
               '2026-08-05 00:00:00-04:00', '2026-08-06 00:00:00-04:00',
               '2026-08-07 00:00:00-04:00', '2026-08-10 00:00:00-04:00',
               '2026-08-11 00:00:00-04:00', '2026-08-12 00:00:00-04:00',
               '2026-08-13 00:00:00-04:00', '2026-08-14 00:00:00-04:00'],
              dtype='datetime64[s, America/New_York]', name='Date', length=251, freq=None)

In [36]:
df.groupby(df.index.month)["Close"].mean().idxmax()

np.int32(7)

In [37]:
df.groupby(df.index.month)["High"].max()

Date
1     277.085768
2     280.147456
3     266.055186
4     275.508349
5     314.728576
6     317.126501
7     344.273097
8     316.017470
9     256.651929
10    276.299373
11    279.618887
12    287.836529
Name: High, dtype: float64

In [38]:
df.groupby(df.index.month)["Low"].min()

Date
1     242.759224
2     254.994942
3     245.072643
4     245.262308
5     274.370331
6     273.514115
7     288.950814
8     222.956408
9     225.118433
10    243.101979
11    264.599780
12    266.225345
Name: Low, dtype: float64

In [39]:
##no. of trading days in each month
df.index.days_in_month

Index([31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       ...
       31, 31, 31, 31, 31, 31, 31, 31, 31, 31],
      dtype='int32', name='Date', length=251)

In [40]:
df.groupby(df.index.month)["Dividends"].sum()

Date
1     0.00
2     0.26
3     0.00
4     0.00
5     0.27
6     0.00
7     0.00
8     0.27
9     0.00
10    0.00
11    0.26
12    0.00
Name: Dividends, dtype: float64

TO GET A TICKER FROM THE COMPANY NAME ENTERED

In [41]:

from yahooquery import search
result=search("microsoft")
result

{'explains': [],
 'count': 15,
 'quotes': [{'exchange': 'NMS',
   'shortname': 'Microsoft Corporation',
   'quoteType': 'EQUITY',
   'symbol': 'MSFT',
   'index': 'quotes',
   'score': 22351.0,
   'typeDisp': 'Equity',
   'longname': 'Microsoft Corporation',
   'exchDisp': 'NASDAQ',
   'sector': 'Technology',
   'sectorDisp': 'Technology',
   'industry': 'Software—Infrastructure',
   'industryDisp': 'Software—Infrastructure',
   'dispSecIndFlag': True,
   'isYahooFinance': True},
  {'exchange': 'GER',
   'shortname': 'MICROSOFT CORP.               R',
   'quoteType': 'EQUITY',
   'symbol': 'MSF.DE',
   'index': 'quotes',
   'score': 20007.0,
   'typeDisp': 'Equity',
   'longname': 'Microsoft Corporation',
   'exchDisp': 'XETRA',
   'sector': 'Technology',
   'sectorDisp': 'Technology',
   'industry': 'Software—Infrastructure',
   'industryDisp': 'Software—Infrastructure',
   'isYahooFinance': True},
  {'exchange': 'NEO',
   'shortname': 'MICROSOFT (MSFT) BMO CDR (CAD H',
   'quoteType': 'EQUITY',
   'symbol': 'ZMSF.NE',
   'index': 'quotes',
   'score': 20006.0,
   'typeDisp': 'Equity',
   'exchDisp': 'NEO',
   'sector': 'Technology',
   'sectorDisp': 'Technology',
   'industry': 'Software—Infrastructure',
   'industryDisp': 'Software—Infrastructure',
   'isYahooFinance': True},
  {'exchange': 'CCC',
   'shortname': 'Microsoft tokenized stock (xStock) USD',
   'quoteType': 'CRYPTOCURRENCY',
   'symbol': 'MSFTX-USD',
   'index': 'quotes',
   'score': 20005.0,
   'typeDisp': 'Cryptocurrency',
   'longname': 'Microsoft tokenized stock (xStock) USD',
   'exchDisp': 'CCC',
   'isYahooFinance': True},
  {'exchange': 'MIL',
   'shortname': 'LEVERAGE SHARES 3X MICROSOFT ET',
   'quoteType': 'ETF',
   'symbol': '3MSF.MI',
   'index': 'quotes',
   'score': 20004.0,
   'typeDisp': 'ETF',
   'longname': 'Leverage Shares 3x Microsoft ETC',
   'exchDisp': 'Milan',
   'isYahooFinance': True},
  {'exchange': 'SAO',
   'shortname': 'MICROSOFT   DRN',
   'quoteType': 'EQUITY',
   'symbol': 'MSFT34.SA',
   'index': 'quotes',
   'score': 20003.0,
   'typeDisp': 'Equity',
   'longname': 'Microsoft Corporation',
   'exchDisp': 'São Paulo',
   'sector': 'Technology',
   'sectorDisp': 'Technology',
   'industry': 'Software—Infrastructure',
   'industryDisp': 'Software—Infrastructure',
   'isYahooFinance': True},
  {'exchange': 'SET',
   'shortname': 'MSFT01_DR MSFT#BLS',
   'quoteType': 'EQUITY',
   'symbol': 'MSFT01.BK',
   'index': 'quotes',
   'score': 20002.0,
   'typeDisp': 'Equity',
   'longname': 'Microsoft Corporation',
   'exchDisp': 'SET',
   'sector': 'Technology',
   'sectorDisp': 'Technology',
   'industry': 'Software—Infrastructure',
   'industryDisp': 'Software—Infrastructure',
   'isYahooFinance': True}],
 'news': [{'uuid': 'f62db4ed-6fcd-3546-8145-639dbd7b1490',
   'title': 'The 5 Biggest Risks Americans Don’t Think About Behind the Data Center Boom',
   'publisher': '24/7 Wall St.',
   'link': 'https://finance.yahoo.com/m/f62db4ed-6fcd-3546-8145-639dbd7b1490/the-5-biggest-risks-americans.html',
   'providerPublishTime': 1786798800,
   'type': 'STORY',
   'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/dseCrjuwD2xf5Bf6oagSMA--~B/aD0xNjAwO3c9Mjg0NDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/24_7_wall_st__718/4e5801942adf37b47805b32793ceff8e.jpg',
      'width': 2844,
      'height': 1600,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/SYjIyKYaquyWItLFr_7Cvw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/24_7_wall_st__718/4e5801942adf37b47805b32793ceff8e.jpg',
      'width': 140,
      'height': 140,
      'tag': '140x140'}]},
   'relatedTickers': ['GOOG', 'MSFT', 'META', 'AMZN', 'NVDA']},
  {'uuid': '937892ea-0787-3208-9ba8-470167c729f1',
   'title': '3 Cloud Computing Stocks to Buy in August',
   'publisher': '24/7 Wall St.',
   'link': 'https://finance.yahoo.com/m/937892ea-0787-3208-9ba8-470167c729f1/3-cloud-computing-stocks-to.html',
   'providerPublishTime': 1786791626,
   'type': 'STORY',
   'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/1H2YBXz8OOxyqkt9lQosoA--~B/aD03Njg7dz0xMzc2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/24_7_wall_st__718/94b90e19878f8100e5e1b86438f18e51',
      'width': 1376,
      'height': 768,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/fSv_Il2JJIV0hjlCXf1fiw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/24_7_wall_st__718/94b90e19878f8100e5e1b86438f18e51',
      'width': 140,
      'height': 140,
      'tag': '140x140'}]},
   'relatedTickers': ['GOOG', 'AMZN', 'MSFT']},
  {'uuid': 'f10220b4-d511-3760-89b2-8ed0ce648c1c',
   'title': "Robert Karr's Second Quarter 2026 Move: Exiting Wix.com Ltd at a -6.67% Portfolio Impact",
   'publisher': 'GuruFocus.com',
   'link': 'https://finance.yahoo.com/markets/stocks/articles/robert-karrs-second-quarter-2026-020310060.html',
   'providerPublishTime': 1786759390,
   'type': 'STORY',
   'relatedTickers': ['MSFT']},
  {'uuid': '92c5d27a-03f8-3904-844d-255352a5ef32',
   'title': '‘Big Short’ investor warns AI boom has quiet weak spot',
   'publisher': 'TheStreet',
   'link': 'https://finance.yahoo.com/m/92c5d27a-03f8-3904-844d-255352a5ef32/%E2%80%98big-short%E2%80%99-investor-warns-ai.html',
   'providerPublishTime': 1786759380,
   'type': 'STORY',
   'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/H2R.xfsunt66zAadtbrHeA--~B/aD0yNTU2O3c9Mzg0MDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/thestreet_881/6c77252dacab2c8644f41611ec49ad88.jpg',
      'width': 3840,
      'height': 2556,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/5yaiiAMUrGoH7RBkwYaSLw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/thestreet_881/6c77252dacab2c8644f41611ec49ad88.jpg',
      'width': 140,
      'height': 140,
      'tag': '140x140'}]},
   'relatedTickers': ['ORCL', 'MSFT', 'AMZN', 'GOOG']},
  {'uuid': '20fd4782-6d40-3b1e-b924-81a187434fd5',
   'title': "Bill Gates's Top Second Quarter 2026 Move: Trims Berkshire Hathaway Inc at a -3.57% Portfolio Impact",
   'publisher': 'GuruFocus.com',
   'link': 'https://finance.yahoo.com/markets/stocks/articles/bill-gatess-top-second-quarter-020121493.html',
   'providerPublishTime': 1786759281,
   'type': 'STORY',
   'relatedTickers': ['BRK-B', 'MSFT', 'HD']},
  {'uuid': '213d6d57-7c02-399b-b3e0-29c50a3a50ae',
   'title': 'Pershing Square Holdings Ltd (LSE:PSH) (Q2 2026) Earnings Call Highlights: Strategic Leverage ...',
   'publisher': 'GuruFocus.com',
   'link': 'https://finance.yahoo.com/markets/stocks/articles/pershing-square-holdings-ltd-lse-010734806.html',
   'providerPublishTime': 1786756054,
   'type': 'STORY',
   'relatedTickers': ['PSH.L', 'AMZN', 'PSHD.L', 'META', 'MSFT', 'ALC']},
  {'uuid': '60691771-bd29-3b34-a33e-fb646bbeb150',
   'title': 'Why AI is unlikely to be an apocalypse for jobs',
   'publisher': 'Investing.com',
   'link': 'https://finance.yahoo.com/technology/ai/articles/why-ai-unlikely-apocalypse-jobs-234216568.html',
   'providerPublishTime': 1786750936,
   'type': 'STORY',
   'relatedTickers': ['BAC', 'GOOG', 'MSFT']},
  {'uuid': '80941763-242e-3a5e-85df-5f7ea52f22ab',
   'title': 'JFrog (FROG) Is Up 7.4% After Raising Guidance On AI-Fueled Cloud Security Demand - Has The Bull Case Changed?',
   'publisher': 'Simply Wall St.',
   'link': 'https://finance.yahoo.com/technology/ai/articles/jfrog-frog-7-4-raising-231159451.html',
   'providerPublishTime': 1786749119,
   'type': 'STORY',
   'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/AteaAjd5GU7lUW.7r_FC3g--~B/aD00MzI7dz0xMTk0O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/simply_wall_st__316/36ca5b522ba2e0a30acf16e5282f313b.jpg',
      'width': 1194,
      'height': 432,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/FmENybbv1Ze6jQQlMGlgkA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/simply_wall_st__316/36ca5b522ba2e0a30acf16e5282f313b.jpg',
      'width': 140,
      'height': 140,
      'tag': '140x140'}]},
   'relatedTickers': ['FROG', 'MSFT', 'NVDA']}],
 'nav': [],
 'lists': [],
 'researchReports': [],
 'screenerFieldResults': [],
 'totalTime': 41,
 'timeTakenForQuotes': 424,
 'timeTakenForNews': 600,
 'timeTakenForAlgowatchlist': 400,
 'timeTakenForPredefinedScreener': 400,
 'timeTakenForCrunchbase': 0,
 'timeTakenForNav': 400,
 'timeTakenForResearchReports': 0,
 'timeTakenForQuestions': 0,
 'timeTakenForScreenerField': 0,
 'timeTakenForCulturalAssets': 0,
 'timeTakenForSearchLists': 0}

In [42]:
x=result.keys()
print(x)
print(result['quotes'])
type(result['quotes'])
"""
the result is a dictionary but the quotes key has a list stored inside it and the list has dicts stored in it as elements so
result(dict)-->quotes(list)--->dict elements
"""

dict_keys(['explains', 'count', 'quotes', 'news', 'nav', 'lists', 'researchReports', 'screenerFieldResults', 'totalTime', 'timeTakenForQuotes', 'timeTakenForNews', 'timeTakenForAlgowatchlist', 'timeTakenForPredefinedScreener', 'timeTakenForCrunchbase', 'timeTakenForNav', 'timeTakenForResearchReports', 'timeTakenForQuestions', 'timeTakenForScreenerField', 'timeTakenForCulturalAssets', 'timeTakenForSearchLists'])
[{'exchange': 'NMS', 'shortname': 'Microsoft Corporation', 'quoteType': 'EQUITY', 'symbol': 'MSFT', 'index': 'quotes', 'score': 22351.0, 'typeDisp': 'Equity', 'longname': 'Microsoft Corporation', 'exchDisp': 'NASDAQ', 'sector': 'Technology', 'sectorDisp': 'Technology', 'industry': 'Software—Infrastructure', 'industryDisp': 'Software—Infrastructure', 'dispSecIndFlag': True, 'isYahooFinance': True}, {'exchange': 'GER', 'shortname': 'MICROSOFT CORP.               R', 'quoteType': 'EQUITY', 'symbol': 'MSF.DE', 'index': 'quotes', 'score': 20007.0, 'typeDisp': 'Equity', 'longname': 'Microsoft Corporation', 'exchDisp': 'XETRA', 'sector': 'Technology', 'sectorDisp': 'Technology', 'industry': 'Software—Infrastructure', 'industryDisp': 'Software—Infrastructure', 'isYahooFinance': True}, {'exchange': 'NEO', 'shortname': 'MICROSOFT (MSFT) BMO CDR (CAD H', 'quoteType': 'EQUITY', 'symbol': 'ZMSF.NE', 'index': 'quotes', 'score': 20006.0, 'typeDisp': 'Equity', 'exchDisp': 'NEO', 'sector': 'Technology', 'sectorDisp': 'Technology', 'industry': 'Software—Infrastructure', 'industryDisp': 'Software—Infrastructure', 'isYahooFinance': True}, {'exchange': 'CCC', 'shortname': 'Microsoft tokenized stock (xStock) USD', 'quoteType': 'CRYPTOCURRENCY', 'symbol': 'MSFTX-USD', 'index': 'quotes', 'score': 20005.0, 'typeDisp': 'Cryptocurrency', 'longname': 'Microsoft tokenized stock (xStock) USD', 'exchDisp': 'CCC', 'isYahooFinance': True}, {'exchange': 'MIL', 'shortname': 'LEVERAGE SHARES 3X MICROSOFT ET', 'quoteType': 'ETF', 'symbol': '3MSF.MI', 'index': 'quotes', 'score': 20004.0, 'typeDisp': 'ETF', 'longname': 'Leverage Shares 3x Microsoft ETC', 'exchDisp': 'Milan', 'isYahooFinance': True}, {'exchange': 'SAO', 'shortname': 'MICROSOFT   DRN', 'quoteType': 'EQUITY', 'symbol': 'MSFT34.SA', 'index': 'quotes', 'score': 20003.0, 'typeDisp': 'Equity', 'longname': 'Microsoft Corporation', 'exchDisp': 'São Paulo', 'sector': 'Technology', 'sectorDisp': 'Technology', 'industry': 'Software—Infrastructure', 'industryDisp': 'Software—Infrastructure', 'isYahooFinance': True}, {'exchange': 'SET', 'shortname': 'MSFT01_DR MSFT#BLS', 'quoteType': 'EQUITY', 'symbol': 'MSFT01.BK', 'index': 'quotes', 'score': 20002.0, 'typeDisp': 'Equity', 'longname': 'Microsoft Corporation', 'exchDisp': 'SET', 'sector': 'Technology', 'sectorDisp': 'Technology', 'industry': 'Software—Infrastructure', 'industryDisp': 'Software—Infrastructure', 'isYahooFinance': True}]

'\nthe result is a dictionary but the quotes key has a list stored inside it and the list has dicts stored in it as elements so\nresult(dict)-->quotes(list)--->dict elements\n'

In [43]:
result['quotes'][0]['symbol']#####found the ticker

'MSFT'

In [44]:
aplr=search("AAPL")
apl=aplr['quotes'][0]['symbol']
apl

'AAPL'

In [49]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.00,0.0
2025-08-18 00:00:00-04:00,230.847254,232.262026,229.263109,230.040237,37476200,0.00,0.0
2025-08-19 00:00:00-04:00,230.428808,232.012952,228.505918,229.711456,39402600,0.00,0.0
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.00,0.0
2025-08-21 00:00:00-04:00,225.437249,225.686329,222.956408,224.072281,30621200,0.00,0.0
...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0