In [1]:
#IMPORT LIBRARIES
import yfinance as yf
import pandas as pd
import numpy as np

In [19]:
df=yf.Ticker("JETS").history(period="1y")
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2025-08-15 00:00:00-04:00,25.193646,25.530884,25.193646,25.451534,4450600,0.0,0.0,0.0
2025-08-18 00:00:00-04:00,25.511046,25.620153,25.243241,25.501127,3390000,0.0,0.0,0.0
2025-08-19 00:00:00-04:00,25.471373,25.788773,25.401942,25.520966,3643700,0.0,0.0,0.0
2025-08-20 00:00:00-04:00,25.292836,25.352348,24.891126,25.015110,3826800,0.0,0.0,0.0
2025-08-21 00:00:00-04:00,24.925840,24.925840,24.618359,24.737385,1986700,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,32.180000,32.250000,31.420000,31.440001,2536400,0.0,0.0,0.0
2026-08-11 00:00:00-04:00,31.570000,31.940001,31.389999,31.700001,1424200,0.0,0.0,0.0
2026-08-12 00:00:00-04:00,31.940001,32.060001,31.360001,31.620001,1487700,0.0,0.0,0.0
2026-08-13 00:00:00-04:00,32.040001,32.169998,31.700001,31.860001,1481000,0.0,0.0,0.0
2026-08-14 00:00:00-04:00,31.809999,31.969999,31.471001,31.559999,904100,0.0,0.0,0.0

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2025-08-15 00:00:00-04:00,25.193646,25.530884,25.193646,25.451534,4450600,0.0,0.0,0.0
2025-08-18 00:00:00-04:00,25.511046,25.620153,25.243241,25.501127,3390000,0.0,0.0,0.0
2025-08-19 00:00:00-04:00,25.471373,25.788773,25.401942,25.520966,3643700,0.0,0.0,0.0
2025-08-20 00:00:00-04:00,25.292836,25.352348,24.891126,25.015110,3826800,0.0,0.0,0.0
2025-08-21 00:00:00-04:00,24.925840,24.925840,24.618359,24.737385,1986700,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,32.180000,32.250000,31.420000,31.440001,2536400,0.0,0.0,0.0
2026-08-11 00:00:00-04:00,31.570000,31.940001,31.389999,31.700001,1424200,0.0,0.0,0.0
2026-08-12 00:00:00-04:00,31.940001,32.060001,31.360001,31.620001,1487700,0.0,0.0,0.0
2026-08-13 00:00:00-04:00,32.040001,32.169998,31.700001,31.860001,1481000,0.0,0.0,0.0
2026-08-14 00:00:00-04:00,31.809999,31.969999,31.471001,31.559999,904100,0.0,0.0,0.0

In [100]:
ohlcv=df[["Open","High","Low","Close","Volume"]]

In [23]:
ohlcv

                                Open       High        Low      Close   Volume
Date
2025-08-15 00:00:00-04:00  25.193646  25.530884  25.193646  25.451534  4450600
2025-08-18 00:00:00-04:00  25.511046  25.620153  25.243241  25.501127  3390000
2025-08-19 00:00:00-04:00  25.471373  25.788773  25.401942  25.520966  3643700
2025-08-20 00:00:00-04:00  25.292836  25.352348  24.891126  25.015110  3826800
2025-08-21 00:00:00-04:00  24.925840  24.925840  24.618359  24.737385  1986700
...                              ...        ...        ...        ...      ...
2026-08-10 00:00:00-04:00  32.180000  32.250000  31.420000  31.440001  2536400
2026-08-11 00:00:00-04:00  31.570000  31.940001  31.389999  31.700001  1424200
2026-08-12 00:00:00-04:00  31.940001  32.060001  31.360001  31.620001  1487700
2026-08-13 00:00:00-04:00  32.040001  32.169998  31.700001  31.860001  1481000
2026-08-14 00:00:00-04:00  31.809999  31.969999  31.471001  31.559999   904100

[251 rows x 5 columns]

In [24]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2025-08-15 00:00:00-04:00,25.193646,25.530884,25.193646,25.451534,4450600,0.0,0.0,0.0
2025-08-18 00:00:00-04:00,25.511046,25.620153,25.243241,25.501127,3390000,0.0,0.0,0.0
2025-08-19 00:00:00-04:00,25.471373,25.788773,25.401942,25.520966,3643700,0.0,0.0,0.0
2025-08-20 00:00:00-04:00,25.292836,25.352348,24.891126,25.015110,3826800,0.0,0.0,0.0
2025-08-21 00:00:00-04:00,24.925840,24.925840,24.618359,24.737385,1986700,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,32.180000,32.250000,31.420000,31.440001,2536400,0.0,0.0,0.0
2026-08-11 00:00:00-04:00,31.570000,31.940001,31.389999,31.700001,1424200,0.0,0.0,0.0
2026-08-12 00:00:00-04:00,31.940001,32.060001,31.360001,31.620001,1487700,0.0,0.0,0.0
2026-08-13 00:00:00-04:00,32.040001,32.169998,31.700001,31.860001,1481000,0.0,0.0,0.0
2026-08-14 00:00:00-04:00,31.809999,31.969999,31.471001,31.559999,904100,0.0,0.0,0.0

In [37]:
#making 2 values in Close NaN
df.loc["2025-08-19 00:00:00-04:00","Close"]=np.nan
df.loc["2025-08-21 00:00:00-04:00","Close"]=np.nan

In [38]:
df["Close"].isna().sum()

np.int64(2)

In [39]:
df[df["Close"].isna()]

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2025-08-19 00:00:00-04:00,25.471373,25.788773,25.401942,NaN,3643700,0.0,0.0,0.0
2025-08-21 00:00:00-04:00,24.925840,24.925840,24.618359,NaN,1986700,0.0,0.0,0.0

In [41]:
df.drop(df.index[df["Close"].isna()])

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2025-08-15 00:00:00-04:00,25.193646,25.530884,25.193646,25.451534,4450600,0.0,0.0,0.0
2025-08-18 00:00:00-04:00,25.511046,25.620153,25.243241,25.501127,3390000,0.0,0.0,0.0
2025-08-20 00:00:00-04:00,25.292836,25.352348,24.891126,25.015110,3826800,0.0,0.0,0.0
2025-08-22 00:00:00-04:00,24.915923,26.026823,24.806816,26.006985,4895400,0.0,0.0,0.0
2025-08-25 00:00:00-04:00,25.749097,25.848284,25.560641,25.570560,1826300,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,32.180000,32.250000,31.420000,31.440001,2536400,0.0,0.0,0.0
2026-08-11 00:00:00-04:00,31.570000,31.940001,31.389999,31.700001,1424200,0.0,0.0,0.0
2026-08-12 00:00:00-04:00,31.940001,32.060001,31.360001,31.620001,1487700,0.0,0.0,0.0
2026-08-13 00:00:00-04:00,32.040001,32.169998,31.700001,31.860001,1481000,0.0,0.0,0.0
2026-08-14 00:00:00-04:00,31.809999,31.969999,31.471001,31.559999,904100,0.0,0.0,0.0

In [46]:
ohlcv.iloc[0,0]

np.float64(25.193646322087197)

In [42]:
ohlcv

                                Open       High        Low      Close   Volume
Date
2025-08-15 00:00:00-04:00  25.193646  25.530884  25.193646  25.451534  4450600
2025-08-18 00:00:00-04:00  25.511046  25.620153  25.243241  25.501127  3390000
2025-08-19 00:00:00-04:00  25.471373  25.788773  25.401942  25.520966  3643700
2025-08-20 00:00:00-04:00  25.292836  25.352348  24.891126  25.015110  3826800
2025-08-21 00:00:00-04:00  24.925840  24.925840  24.618359  24.737385  1986700
...                              ...        ...        ...        ...      ...
2026-08-10 00:00:00-04:00  32.180000  32.250000  31.420000  31.440001  2536400
2026-08-11 00:00:00-04:00  31.570000  31.940001  31.389999  31.700001  1424200
2026-08-12 00:00:00-04:00  31.940001  32.060001  31.360001  31.620001  1487700
2026-08-13 00:00:00-04:00  32.040001  32.169998  31.700001  31.860001  1481000
2026-08-14 00:00:00-04:00  31.809999  31.969999  31.471001  31.559999   904100

[251 rows x 5 columns]

In [101]:
for j in [1,3,6,7]:
    for i in [0,1,3]:
        ohlcv.iloc[j,i]=np.nan

In [102]:
ohlcv

                                Open       High        Low      Close   Volume
Date
2025-08-15 00:00:00-04:00  25.193646  25.530884  25.193646  25.451534  4450600
2025-08-18 00:00:00-04:00        NaN        NaN  25.243241        NaN  3390000
2025-08-19 00:00:00-04:00  25.471373  25.788773  25.401942        NaN  3643700
2025-08-20 00:00:00-04:00        NaN        NaN  24.891126        NaN  3826800
2025-08-21 00:00:00-04:00  24.925840  24.925840  24.618359        NaN  1986700
...                              ...        ...        ...        ...      ...
2026-08-10 00:00:00-04:00  32.180000  32.250000  31.420000  31.440001  2536400
2026-08-11 00:00:00-04:00  31.570000  31.940001  31.389999  31.700001  1424200
2026-08-12 00:00:00-04:00  31.940001  32.060001  31.360001  31.620001  1487700
2026-08-13 00:00:00-04:00  32.040001  32.169998  31.700001  31.860001  1481000
2026-08-14 00:00:00-04:00  31.809999  31.969999  31.471001  31.559999   904100

[251 rows x 5 columns]

In [103]:
ohlcv.iloc[1,:].isna().sum()

np.int64(3)

In [93]:
ohlcv.index

DatetimeIndex(['2025-08-15 00:00:00-04:00', '2025-08-19 00:00:00-04:00',
               '2025-08-21 00:00:00-04:00', '2025-08-22 00:00:00-04:00',
               '2025-08-27 00:00:00-04:00', '2025-08-28 00:00:00-04:00',
               '2025-08-29 00:00:00-04:00', '2025-09-02 00:00:00-04:00',
               '2025-09-03 00:00:00-04:00', '2025-09-04 00:00:00-04:00',
               ...
               '2026-08-03 00:00:00-04:00', '2026-08-04 00:00:00-04:00',
               '2026-08-05 00:00:00-04:00', '2026-08-06 00:00:00-04:00',
               '2026-08-07 00:00:00-04:00', '2026-08-10 00:00:00-04:00',
               '2026-08-11 00:00:00-04:00', '2026-08-12 00:00:00-04:00',
               '2026-08-13 00:00:00-04:00', '2026-08-14 00:00:00-04:00'],
              dtype='datetime64[s, America/New_York]', name='Date', length=247, freq=None)

In [104]:
ohlcv.isna().sum(axis=1)

Date
2025-08-15 00:00:00-04:00    0
2025-08-18 00:00:00-04:00    3
2025-08-19 00:00:00-04:00    1
2025-08-20 00:00:00-04:00    3
2025-08-21 00:00:00-04:00    1
                            ..
2026-08-10 00:00:00-04:00    0
2026-08-11 00:00:00-04:00    0
2026-08-12 00:00:00-04:00    0
2026-08-13 00:00:00-04:00    0
2026-08-14 00:00:00-04:00    0
Length: 251, dtype: int64

In [105]:
rows_to_drop=[]#cannot drop rows from original database in loop coz then the index positions change
for i in range(len(ohlcv)):
    if (ohlcv.iloc[i,:].isna().sum())>=3:
        rows_to_drop.append(ohlcv.index[i])
ohlcv.drop(rows_to_drop,inplace=True)

In [107]:
ohlcv.isna().sum(axis=0)

Open      0
High      0
Low       0
Close     2
Volume    0
dtype: int64

In [108]:
rows_to_drop_indf=[]
for i in range(len(df.index)):
    if (df.index[i] not in ohlcv.index):
        rows_to_drop_indf.append(df.index[i])
df.drop(rows_to_drop_indf,inplace=True)

In [109]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2025-08-15 00:00:00-04:00,25.193646,25.530884,25.193646,25.451534,4450600,0.0,0.0,0.0
2025-08-19 00:00:00-04:00,25.471373,25.788773,25.401942,NaN,3643700,0.0,0.0,0.0
2025-08-21 00:00:00-04:00,24.925840,24.925840,24.618359,NaN,1986700,0.0,0.0,0.0
2025-08-22 00:00:00-04:00,24.915923,26.026823,24.806816,26.006985,4895400,0.0,0.0,0.0
2025-08-27 00:00:00-04:00,25.828450,26.150808,25.818531,25.917717,2002200,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,32.180000,32.250000,31.420000,31.440001,2536400,0.0,0.0,0.0
2026-08-11 00:00:00-04:00,31.570000,31.940001,31.389999,31.700001,1424200,0.0,0.0,0.0
2026-08-12 00:00:00-04:00,31.940001,32.060001,31.360001,31.620001,1487700,0.0,0.0,0.0
2026-08-13 00:00:00-04:00,32.040001,32.169998,31.700001,31.860001,1481000,0.0,0.0,0.0
2026-08-14 00:00:00-04:00,31.809999,31.969999,31.471001,31.559999,904100,0.0,0.0,0.0

In [110]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2025-08-15 00:00:00-04:00,25.193646,25.530884,25.193646,25.451534,4450600,0.0,0.0,0.0
2025-08-19 00:00:00-04:00,25.471373,25.788773,25.401942,NaN,3643700,0.0,0.0,0.0
2025-08-21 00:00:00-04:00,24.925840,24.925840,24.618359,NaN,1986700,0.0,0.0,0.0
2025-08-22 00:00:00-04:00,24.915923,26.026823,24.806816,26.006985,4895400,0.0,0.0,0.0
2025-08-27 00:00:00-04:00,25.828450,26.150808,25.818531,25.917717,2002200,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,32.180000,32.250000,31.420000,31.440001,2536400,0.0,0.0,0.0
2026-08-11 00:00:00-04:00,31.570000,31.940001,31.389999,31.700001,1424200,0.0,0.0,0.0
2026-08-12 00:00:00-04:00,31.940001,32.060001,31.360001,31.620001,1487700,0.0,0.0,0.0
2026-08-13 00:00:00-04:00,32.040001,32.169998,31.700001,31.860001,1481000,0.0,0.0,0.0
2026-08-14 00:00:00-04:00,31.809999,31.969999,31.471001,31.559999,904100,0.0,0.0,0.0

In [111]:
df=yf.Ticker("AAPL").history(period="1y")

In [112]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.00,0.0
2025-08-18 00:00:00-04:00,230.847239,232.262011,229.263094,230.040222,37476200,0.00,0.0
2025-08-19 00:00:00-04:00,230.428808,232.012952,228.505918,229.711456,39402600,0.00,0.0
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.00,0.0
2025-08-21 00:00:00-04:00,225.437234,225.686314,222.956393,224.072266,30621200,0.00,0.0
...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0

In [113]:
bad_df = df.copy()

bad_df = pd.concat([bad_df, bad_df.iloc[[20]]])

print("Duplicate indexes:", bad_df.index.duplicated().sum())

Duplicate indexes: 1

In [114]:
bad_df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.0,0.0
2025-08-18 00:00:00-04:00,230.847239,232.262011,229.263094,230.040222,37476200,0.0,0.0
2025-08-19 00:00:00-04:00,230.428808,232.012952,228.505918,229.711456,39402600,0.0,0.0
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.0,0.0
2025-08-21 00:00:00-04:00,225.437234,225.686314,222.956393,224.072266,30621200,0.0,0.0
...,...,...,...,...,...,...,...
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.0,0.0
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.0,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.0,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.0,0.0
2025-09-15 00:00:00-04:00,236.127741,237.313364,234.164990,235.828842,42699500,0.0,0.0

In [134]:
bad_df[bad_df.index.duplicated(keep=False)]
bad_df.index.drop_duplicates()###shows unique indexes doesnt remove them
bad_df=bad_df[~bad_df.index.duplicated(keep="first")]

In [136]:
bad_df.duplicated().sum()

np.int64(0)

In [137]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-08-15 00:00:00-04:00,233.138790,233.417758,228.495937,230.737656,56038700,0.00,0.0
2025-08-18 00:00:00-04:00,230.847239,232.262011,229.263094,230.040222,37476200,0.00,0.0
2025-08-19 00:00:00-04:00,230.428808,232.012952,228.505918,229.711456,39402600,0.00,0.0
2025-08-20 00:00:00-04:00,229.133582,229.621784,224.939085,225.178192,42263900,0.00,0.0
2025-08-21 00:00:00-04:00,225.437234,225.686314,222.956393,224.072266,30621200,0.00,0.0
...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0