In [8]:
import pandas as pd
import numpy as np
import yfinance as yf
df=yf.Ticker("AAPL").history(period="2y")
price_metrics=pd.DataFrame()
price_metrics["daily_change"]=[]
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-08-15 00:00:00-04:00,222.736774,223.480552,220.912027,222.855774,46414000,0.00,0.0
2024-08-16 00:00:00-04:00,222.062394,224.948256,221.794629,224.174728,44340200,0.00,0.0
2024-08-19 00:00:00-04:00,223.847464,224.115229,221.189689,224.016052,40687800,0.00,0.0
2024-08-20 00:00:00-04:00,223.897054,225.285434,223.579701,224.630905,30299000,0.00,0.0
2024-08-21 00:00:00-04:00,224.640835,226.088714,223.183029,224.521820,34765500,0.00,0.0
...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0

In [23]:

price_metrics["daily_change"]=df["Close"].diff()
price_metrics["daily_return"]=df["Close"].pct_change()
price_metrics

                           daily_change  daily_return  daily_range
Date
2024-08-15 00:00:00-04:00           NaN           NaN     2.568525
2024-08-16 00:00:00-04:00      1.318954      0.005918     3.153627
2024-08-19 00:00:00-04:00     -0.158676     -0.000708     2.925539
2024-08-20 00:00:00-04:00      0.614853      0.002745     1.705732
2024-08-21 00:00:00-04:00     -0.109085     -0.000486     2.905686
...                                 ...           ...          ...
2026-08-10 00:00:00-04:00     -4.799988     -0.015332     3.650024
2026-08-11 00:00:00-04:00     -3.350006     -0.010867     7.179993
2026-08-12 00:00:00-04:00     -2.660004     -0.008724     5.089996
2026-08-13 00:00:00-04:00      3.010010      0.009959     3.950012
2026-08-14 00:00:00-04:00      0.669983      0.002195     3.190002

[501 rows x 3 columns]

In [24]:
price_metrics["daily_range"]=df["High"]-df["Low"]

In [25]:
price_metrics

                           daily_change  daily_return  daily_range
Date
2024-08-15 00:00:00-04:00           NaN           NaN     2.568525
2024-08-16 00:00:00-04:00      1.318954      0.005918     3.153627
2024-08-19 00:00:00-04:00     -0.158676     -0.000708     2.925539
2024-08-20 00:00:00-04:00      0.614853      0.002745     1.705732
2024-08-21 00:00:00-04:00     -0.109085     -0.000486     2.905686
...                                 ...           ...          ...
2026-08-10 00:00:00-04:00     -4.799988     -0.015332     3.650024
2026-08-11 00:00:00-04:00     -3.350006     -0.010867     7.179993
2026-08-12 00:00:00-04:00     -2.660004     -0.008724     5.089996
2026-08-13 00:00:00-04:00      3.010010      0.009959     3.950012
2026-08-14 00:00:00-04:00      0.669983      0.002195     3.190002

[501 rows x 3 columns]

In [26]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-08-15 00:00:00-04:00,222.736774,223.480552,220.912027,222.855774,46414000,0.00,0.0
2024-08-16 00:00:00-04:00,222.062394,224.948256,221.794629,224.174728,44340200,0.00,0.0
2024-08-19 00:00:00-04:00,223.847464,224.115229,221.189689,224.016052,40687800,0.00,0.0
2024-08-20 00:00:00-04:00,223.897054,225.285434,223.579701,224.630905,30299000,0.00,0.0
2024-08-21 00:00:00-04:00,224.640835,226.088714,223.183029,224.521820,34765500,0.00,0.0
...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0

In [36]:
price_metrics["cumulative_return"]=(df.iloc[:,3]-df.iloc[0,3])/(df.iloc[0,3])

In [38]:
price_metrics

,daily_change,daily_return,daily_range,cumulative_return
Date,,,,
2024-08-15 00:00:00-04:00,NaN,NaN,2.568525,0.000000
2024-08-16 00:00:00-04:00,1.318954,0.005918,3.153627,0.005918
2024-08-19 00:00:00-04:00,-0.158676,-0.000708,2.925539,0.005206
2024-08-20 00:00:00-04:00,0.614853,0.002745,1.705732,0.007965
2024-08-21 00:00:00-04:00,-0.109085,-0.000486,2.905686,0.007476
...,...,...,...,...
2026-08-10 00:00:00-04:00,-4.799988,-0.015332,3.650024,0.383226
2026-08-11 00:00:00-04:00,-3.350006,-0.010867,7.179993,0.368194
2026-08-12 00:00:00-04:00,-2.660004,-0.008724,5.089996,0.356258
2026-08-13 00:00:00-04:00,3.010010,0.009959,3.950012,0.369765
2026-08-14 00:00:00-04:00,0.669983,0.002195,3.190002,0.372771

In [39]:
moving_averages=pd.DataFrame()

In [41]:
moving_averages["SMA_20"]=df["Close"].rolling(20).mean()

In [42]:
moving_averages

                               SMA_20
Date
2024-08-15 00:00:00-04:00         NaN
2024-08-16 00:00:00-04:00         NaN
2024-08-19 00:00:00-04:00         NaN
2024-08-20 00:00:00-04:00         NaN
2024-08-21 00:00:00-04:00         NaN
...                               ...
2026-08-10 00:00:00-04:00  322.713972
2026-08-11 00:00:00-04:00  322.230038
2026-08-12 00:00:00-04:00  320.981648
2026-08-13 00:00:00-04:00  319.596007
2026-08-14 00:00:00-04:00  318.219887

[501 rows x 1 columns]

In [44]:
moving_averages.isna().sum()

SMA_20    19
dtype: int64

In [45]:
df=yf.Ticker("AAPL").history(period="max")

In [51]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-12-12 00:00:00-05:00,0.098122,0.098549,0.098122,0.098122,469033600,0.00,0.0
1980-12-15 00:00:00-05:00,0.093430,0.093430,0.093003,0.093003,175884800,0.00,0.0
1980-12-16 00:00:00-05:00,0.086604,0.086604,0.086177,0.086177,105728000,0.00,0.0
1980-12-17 00:00:00-05:00,0.088310,0.088737,0.088310,0.088310,86441600,0.00,0.0
1980-12-18 00:00:00-05:00,0.090870,0.091297,0.090870,0.090870,73449600,0.00,0.0
...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0

In [57]:
moving_averages=pd.DataFrame()
moving_averages["SMA_20"]=df["Close"].rolling(20).mean()
moving_averages["SMA_50"]=df["Close"].rolling(50).mean()
moving_averages["SMA_200"]=df["Close"].rolling(200).mean()

In [58]:
moving_averages

                               SMA_20      SMA_50     SMA_200
Date
1980-12-12 00:00:00-05:00         NaN         NaN         NaN
1980-12-15 00:00:00-05:00         NaN         NaN         NaN
1980-12-16 00:00:00-05:00         NaN         NaN         NaN
1980-12-17 00:00:00-05:00         NaN         NaN         NaN
1980-12-18 00:00:00-05:00         NaN         NaN         NaN
...                               ...         ...         ...
2026-08-10 00:00:00-04:00  322.713972  309.438845  279.123043
2026-08-11 00:00:00-04:00  322.230038  309.301223  279.360099
2026-08-12 00:00:00-04:00  320.981648  309.225302  279.578226
2026-08-13 00:00:00-04:00  319.596007  309.031934  279.795263
2026-08-14 00:00:00-04:00  318.219887  308.950681  279.985809

[11510 rows x 3 columns]

In [64]:
moving_averages["EMA_200"]=df["Close"].ewm(span=200,adjust=False).mean()

In [65]:
moving_averages

,SMA_20,SMA_50,SMA_200,EMA_20,EMA_200
Date,,,,,
1980-12-12 00:00:00-05:00,NaN,NaN,NaN,0.098122,0.098122
1980-12-15 00:00:00-05:00,NaN,NaN,NaN,0.097635,0.098071
1980-12-16 00:00:00-05:00,NaN,NaN,NaN,0.096544,0.097953
1980-12-17 00:00:00-05:00,NaN,NaN,NaN,0.095760,0.097857
1980-12-18 00:00:00-05:00,NaN,NaN,NaN,0.095294,0.097788
...,...,...,...,...,...
2026-08-10 00:00:00-04:00,322.713972,309.438845,279.123043,316.647037,280.333879
2026-08-11 00:00:00-04:00,322.230038,309.301223,279.360099,315.529224,280.578417
2026-08-12 00:00:00-04:00,320.981648,309.225302,279.578226,314.264536,280.794055
2026-08-13 00:00:00-04:00,319.596007,309.031934,279.795263,313.406962,281.037497
2026-08-14 00:00:00-04:00,318.219887,308.950681,279.985809,312.694870,281.285184

In [66]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-12-12 00:00:00-05:00,0.098122,0.098549,0.098122,0.098122,469033600,0.00,0.0
1980-12-15 00:00:00-05:00,0.093430,0.093430,0.093003,0.093003,175884800,0.00,0.0
1980-12-16 00:00:00-05:00,0.086604,0.086604,0.086177,0.086177,105728000,0.00,0.0
1980-12-17 00:00:00-05:00,0.088310,0.088737,0.088310,0.088310,86441600,0.00,0.0
1980-12-18 00:00:00-05:00,0.090870,0.091297,0.090870,0.090870,73449600,0.00,0.0
...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0

In [74]:
momentum=pd.DataFrame()
momentum["5D"]=df["Close"].pct_change(5)
momentum["20D"]=df["Close"].pct_change(20)
momentum["30D"]=df["Close"].pct_change(30)
momentum["90D"]=df["Close"].pct_change(90)

In [75]:
momentum

                                 5D       20D       30D       90D
Date
1980-12-12 00:00:00-05:00       NaN       NaN       NaN       NaN
1980-12-15 00:00:00-05:00       NaN       NaN       NaN       NaN
1980-12-16 00:00:00-05:00       NaN       NaN       NaN       NaN
1980-12-17 00:00:00-05:00       NaN       NaN       NaN       NaN
1980-12-18 00:00:00-05:00       NaN       NaN       NaN       NaN
...                             ...       ...       ...       ...
2026-08-10 00:00:00-04:00  0.016828 -0.027683  0.087201  0.216794
2026-08-11 00:00:00-04:00 -0.013598 -0.030766  0.083172  0.194907
2026-08-12 00:00:00-04:00 -0.027297 -0.076303  0.045447  0.183141
2026-08-13 00:00:00-04:00 -0.022044 -0.083228  0.037853  0.181352
2026-08-14 00:00:00-04:00 -0.022775 -0.082538 -0.007893  0.208978

[11510 rows x 4 columns]

In [76]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-12-12 00:00:00-05:00,0.098122,0.098549,0.098122,0.098122,469033600,0.00,0.0
1980-12-15 00:00:00-05:00,0.093430,0.093430,0.093003,0.093003,175884800,0.00,0.0
1980-12-16 00:00:00-05:00,0.086604,0.086604,0.086177,0.086177,105728000,0.00,0.0
1980-12-17 00:00:00-05:00,0.088310,0.088737,0.088310,0.088310,86441600,0.00,0.0
1980-12-18 00:00:00-05:00,0.090870,0.091297,0.090870,0.090870,73449600,0.00,0.0
...,...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,306.829987,308.260010,304.609985,308.260010,44812500,0.27,0.0
2026-08-11 00:00:00-04:00,307.750000,309.970001,302.790009,304.910004,37476700,0.00,0.0
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.00,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.00,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28186700,0.00,0.0

In [151]:
rsi=pd.DataFrame()

In [152]:
rsi["Close"]=df["Close"]

In [153]:
rsi

                                Close
Date
1980-12-12 00:00:00-05:00    0.098122
1980-12-15 00:00:00-05:00    0.093003
1980-12-16 00:00:00-05:00    0.086177
1980-12-17 00:00:00-05:00    0.088310
1980-12-18 00:00:00-05:00    0.090870
...                               ...
2026-08-10 00:00:00-04:00  308.260010
2026-08-11 00:00:00-04:00  304.910004
2026-08-12 00:00:00-04:00  302.250000
2026-08-13 00:00:00-04:00  305.260010
2026-08-14 00:00:00-04:00  305.929993

[11510 rows x 1 columns]

In [154]:
rsi["change"]=rsi["Close"].diff()

In [155]:
rsi

                                Close    change
Date
1980-12-12 00:00:00-05:00    0.098122       NaN
1980-12-15 00:00:00-05:00    0.093003 -0.005119
1980-12-16 00:00:00-05:00    0.086177 -0.006826
1980-12-17 00:00:00-05:00    0.088310  0.002133
1980-12-18 00:00:00-05:00    0.090870  0.002560
...                               ...       ...
2026-08-10 00:00:00-04:00  308.260010 -4.799988
2026-08-11 00:00:00-04:00  304.910004 -3.350006
2026-08-12 00:00:00-04:00  302.250000 -2.660004
2026-08-13 00:00:00-04:00  305.260010  3.010010
2026-08-14 00:00:00-04:00  305.929993  0.669983

[11510 rows x 2 columns]

In [156]:

rsi["gain"]=np.where(rsi["change"]>0,rsi["change"],0)
rsi["loss"]=np.where(rsi['change']<0,-rsi['change'],0)
rsi.loc[rsi.index[0],["gain","loss"]]=np.nan

In [157]:
rsi

                                Close    change      gain      loss
Date
1980-12-12 00:00:00-05:00    0.098122       NaN       NaN       NaN
1980-12-15 00:00:00-05:00    0.093003 -0.005119  0.000000  0.005119
1980-12-16 00:00:00-05:00    0.086177 -0.006826  0.000000  0.006826
1980-12-17 00:00:00-05:00    0.088310  0.002133  0.002133  0.000000
1980-12-18 00:00:00-05:00    0.090870  0.002560  0.002560  0.000000
...                               ...       ...       ...       ...
2026-08-10 00:00:00-04:00  308.260010 -4.799988  0.000000  4.799988
2026-08-11 00:00:00-04:00  304.910004 -3.350006  0.000000  3.350006
2026-08-12 00:00:00-04:00  302.250000 -2.660004  0.000000  2.660004
2026-08-13 00:00:00-04:00  305.260010  3.010010  3.010010  0.000000
2026-08-14 00:00:00-04:00  305.929993  0.669983  0.669983  0.000000

[11510 rows x 4 columns]

In [158]:
rsi['14d_gainmean']=rsi["gain"].rolling(14).mean()
rsi['14d_lossmean']=rsi["loss"].rolling(14).mean()
rsi

,Close,change,gain,loss,14d_gainmean,14d_lossmean
Date,,,,,,
1980-12-12 00:00:00-05:00,0.098122,NaN,NaN,NaN,NaN,NaN
1980-12-15 00:00:00-05:00,0.093003,-0.005119,0.000000,0.005119,NaN,NaN
1980-12-16 00:00:00-05:00,0.086177,-0.006826,0.000000,0.006826,NaN,NaN
1980-12-17 00:00:00-05:00,0.088310,0.002133,0.002133,0.000000,NaN,NaN
1980-12-18 00:00:00-05:00,0.090870,0.002560,0.002560,0.000000,NaN,NaN
...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,308.260010,-4.799988,0.000000,4.799988,2.021822,3.393077
2026-08-11 00:00:00-04:00,304.910004,-3.350006,0.000000,3.350006,2.021822,3.500336
2026-08-12 00:00:00-04:00,302.250000,-2.660004,0.000000,2.660004,2.021822,3.388454
2026-08-13 00:00:00-04:00,305.260010,3.010010,3.010010,0.000000,1.426095,3.388454
2026-08-14 00:00:00-04:00,305.929993,0.669983,0.669983,0.000000,1.196333,3.388454

In [159]:

rsi

,Close,change,gain,loss,14d_gainmean,14d_lossmean
Date,,,,,,
1980-12-12 00:00:00-05:00,0.098122,NaN,NaN,NaN,NaN,NaN
1980-12-15 00:00:00-05:00,0.093003,-0.005119,0.000000,0.005119,NaN,NaN
1980-12-16 00:00:00-05:00,0.086177,-0.006826,0.000000,0.006826,NaN,NaN
1980-12-17 00:00:00-05:00,0.088310,0.002133,0.002133,0.000000,NaN,NaN
1980-12-18 00:00:00-05:00,0.090870,0.002560,0.002560,0.000000,NaN,NaN
...,...,...,...,...,...,...
2026-08-10 00:00:00-04:00,308.260010,-4.799988,0.000000,4.799988,2.021822,3.393077
2026-08-11 00:00:00-04:00,304.910004,-3.350006,0.000000,3.350006,2.021822,3.500336
2026-08-12 00:00:00-04:00,302.250000,-2.660004,0.000000,2.660004,2.021822,3.388454
2026-08-13 00:00:00-04:00,305.260010,3.010010,3.010010,0.000000,1.426095,3.388454
2026-08-14 00:00:00-04:00,305.929993,0.669983,0.669983,0.000000,1.196333,3.388454

In [ ]:
rsi["wilder_averagegain"]=np.nan
rsi["wilder_averageloss"]=np.nan
first_valid = rsi["14d_gainmean"].first_valid_index()