In [2]:
import pandas as pd
import numpy as np
import yfinance as yf
df=yf.Ticker("AAPL").history(period="2y")
price_metrics=pd.DataFrame()
price_metrics["daily_change"]=[]
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-08-19 00:00:00-04:00,223.847464,224.115229,221.189689,224.016052,40687800,0.0,0.0
2024-08-20 00:00:00-04:00,223.897069,225.285449,223.579716,224.630920,30299000,0.0,0.0
2024-08-21 00:00:00-04:00,224.640835,226.088714,223.183029,224.521820,34765500,0.0,0.0
2024-08-22 00:00:00-04:00,225.900324,226.445765,222.042595,222.667374,43695300,0.0,0.0
2024-08-23 00:00:00-04:00,223.787957,226.326717,222.468988,224.958160,38677300,0.0,0.0
...,...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.0,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.0,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28229400,0.0,0.0
2026-08-17 00:00:00-04:00,306.209991,307.660004,302.940002,305.589996,38137700,0.0,0.0
2026-08-18 00:00:00-04:00,307.529999,311.489990,305.739990,309.890106,20433651,0.0,0.0

In [3]:

price_metrics["daily_change"]=df["Close"].diff()
price_metrics["daily_return"]=df["Close"].pct_change()
price_metrics

                           daily_change  daily_return
Date
2024-08-19 00:00:00-04:00           NaN           NaN
2024-08-20 00:00:00-04:00      0.614868      0.002745
2024-08-21 00:00:00-04:00     -0.109100     -0.000486
2024-08-22 00:00:00-04:00     -1.854446     -0.008260
2024-08-23 00:00:00-04:00      2.290787      0.010288
...                                 ...           ...
2026-08-12 00:00:00-04:00     -2.660004     -0.008724
2026-08-13 00:00:00-04:00      3.010010      0.009959
2026-08-14 00:00:00-04:00      0.669983      0.002195
2026-08-17 00:00:00-04:00     -0.339996     -0.001111
2026-08-18 00:00:00-04:00      4.300110      0.014072

[501 rows x 2 columns]

In [4]:
price_metrics["daily_range"]=df["High"]-df["Low"]

In [5]:
price_metrics

                           daily_change  daily_return  daily_range
Date
2024-08-19 00:00:00-04:00           NaN           NaN     2.925539
2024-08-20 00:00:00-04:00      0.614868      0.002745     1.705732
2024-08-21 00:00:00-04:00     -0.109100     -0.000486     2.905686
2024-08-22 00:00:00-04:00     -1.854446     -0.008260     4.403170
2024-08-23 00:00:00-04:00      2.290787      0.010288     3.857728
...                                 ...           ...          ...
2026-08-12 00:00:00-04:00     -2.660004     -0.008724     5.089996
2026-08-13 00:00:00-04:00      3.010010      0.009959     3.950012
2026-08-14 00:00:00-04:00      0.669983      0.002195     3.190002
2026-08-17 00:00:00-04:00     -0.339996     -0.001111     4.720001
2026-08-18 00:00:00-04:00      4.300110      0.014072     5.750000

[501 rows x 3 columns]

In [6]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-08-19 00:00:00-04:00,223.847464,224.115229,221.189689,224.016052,40687800,0.0,0.0
2024-08-20 00:00:00-04:00,223.897069,225.285449,223.579716,224.630920,30299000,0.0,0.0
2024-08-21 00:00:00-04:00,224.640835,226.088714,223.183029,224.521820,34765500,0.0,0.0
2024-08-22 00:00:00-04:00,225.900324,226.445765,222.042595,222.667374,43695300,0.0,0.0
2024-08-23 00:00:00-04:00,223.787957,226.326717,222.468988,224.958160,38677300,0.0,0.0
...,...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.0,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.0,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28229400,0.0,0.0
2026-08-17 00:00:00-04:00,306.209991,307.660004,302.940002,305.589996,38137700,0.0,0.0
2026-08-18 00:00:00-04:00,307.529999,311.489990,305.739990,309.890106,20433651,0.0,0.0

In [7]:
price_metrics["cumulative_return"]=(df.iloc[:,3]-df.iloc[0,3])/(df.iloc[0,3])

In [8]:
price_metrics

,daily_change,daily_return,daily_range,cumulative_return
Date,,,,
2024-08-19 00:00:00-04:00,NaN,NaN,2.925539,0.000000
2024-08-20 00:00:00-04:00,0.614868,0.002745,1.705732,0.002745
2024-08-21 00:00:00-04:00,-0.109100,-0.000486,2.905686,0.002258
2024-08-22 00:00:00-04:00,-1.854446,-0.008260,4.403170,-0.006020
2024-08-23 00:00:00-04:00,2.290787,0.010288,3.857728,0.004206
...,...,...,...,...
2026-08-12 00:00:00-04:00,-2.660004,-0.008724,5.089996,0.349234
2026-08-13 00:00:00-04:00,3.010010,0.009959,3.950012,0.362670
2026-08-14 00:00:00-04:00,0.669983,0.002195,3.190002,0.365661
2026-08-17 00:00:00-04:00,-0.339996,-0.001111,4.720001,0.364143
2026-08-18 00:00:00-04:00,4.300110,0.014072,5.750000,0.383339

In [9]:
moving_averages=pd.DataFrame()

In [10]:
moving_averages["SMA_20"]=df["Close"].rolling(20).mean()

In [11]:
moving_averages

                               SMA_20
Date
2024-08-19 00:00:00-04:00         NaN
2024-08-20 00:00:00-04:00         NaN
2024-08-21 00:00:00-04:00         NaN
2024-08-22 00:00:00-04:00         NaN
2024-08-23 00:00:00-04:00         NaN
...                               ...
2026-08-12 00:00:00-04:00  320.981648
2026-08-13 00:00:00-04:00  319.596007
2026-08-14 00:00:00-04:00  318.219887
2026-08-17 00:00:00-04:00  317.183958
2026-08-18 00:00:00-04:00  316.305585

[501 rows x 1 columns]

In [12]:
moving_averages.isna().sum()

SMA_20    19
dtype: int64

In [13]:
df=yf.Ticker("AAPL").history(period="max")

In [14]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-12-12 00:00:00-05:00,0.098122,0.098549,0.098122,0.098122,469033600,0.0,0.0
1980-12-15 00:00:00-05:00,0.093430,0.093430,0.093003,0.093003,175884800,0.0,0.0
1980-12-16 00:00:00-05:00,0.086604,0.086604,0.086177,0.086177,105728000,0.0,0.0
1980-12-17 00:00:00-05:00,0.088310,0.088737,0.088310,0.088310,86441600,0.0,0.0
1980-12-18 00:00:00-05:00,0.090870,0.091297,0.090870,0.090870,73449600,0.0,0.0
...,...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.0,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.0,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28229400,0.0,0.0
2026-08-17 00:00:00-04:00,306.209991,307.660004,302.940002,305.589996,38137700,0.0,0.0
2026-08-18 00:00:00-04:00,307.529999,311.489990,305.739990,309.890106,20433651,0.0,0.0

In [15]:
moving_averages=pd.DataFrame()
moving_averages["SMA_20"]=df["Close"].rolling(20).mean()
moving_averages["SMA_50"]=df["Close"].rolling(50).mean()
moving_averages["SMA_200"]=df["Close"].rolling(200).mean()

In [16]:
moving_averages

                               SMA_20      SMA_50     SMA_200
Date
1980-12-12 00:00:00-05:00         NaN         NaN         NaN
1980-12-15 00:00:00-05:00         NaN         NaN         NaN
1980-12-16 00:00:00-05:00         NaN         NaN         NaN
1980-12-17 00:00:00-05:00         NaN         NaN         NaN
1980-12-18 00:00:00-05:00         NaN         NaN         NaN
...                               ...         ...         ...
2026-08-12 00:00:00-04:00  320.981648  309.225302  279.578227
2026-08-13 00:00:00-04:00  319.596007  309.031934  279.795263
2026-08-14 00:00:00-04:00  318.219887  308.950681  279.985809
2026-08-17 00:00:00-04:00  317.183958  308.843245  280.173710
2026-08-18 00:00:00-04:00  316.305585  308.899543  280.379623

[11512 rows x 3 columns]

In [17]:
moving_averages["EMA_200"]=df["Close"].ewm(span=200,adjust=False).mean()

In [18]:
moving_averages

                               SMA_20      SMA_50     SMA_200     EMA_200
Date
1980-12-12 00:00:00-05:00         NaN         NaN         NaN    0.098122
1980-12-15 00:00:00-05:00         NaN         NaN         NaN    0.098071
1980-12-16 00:00:00-05:00         NaN         NaN         NaN    0.097953
1980-12-17 00:00:00-05:00         NaN         NaN         NaN    0.097857
1980-12-18 00:00:00-05:00         NaN         NaN         NaN    0.097788
...                               ...         ...         ...         ...
2026-08-12 00:00:00-04:00  320.981648  309.225302  279.578227  280.794055
2026-08-13 00:00:00-04:00  319.596007  309.031934  279.795263  281.037497
2026-08-14 00:00:00-04:00  318.219887  308.950681  279.985809  281.285184
2026-08-17 00:00:00-04:00  317.183958  308.843245  280.173710  281.527023
2026-08-18 00:00:00-04:00  316.305585  308.899543  280.379623  281.809243

[11512 rows x 4 columns]

In [19]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-12-12 00:00:00-05:00,0.098122,0.098549,0.098122,0.098122,469033600,0.0,0.0
1980-12-15 00:00:00-05:00,0.093430,0.093430,0.093003,0.093003,175884800,0.0,0.0
1980-12-16 00:00:00-05:00,0.086604,0.086604,0.086177,0.086177,105728000,0.0,0.0
1980-12-17 00:00:00-05:00,0.088310,0.088737,0.088310,0.088310,86441600,0.0,0.0
1980-12-18 00:00:00-05:00,0.090870,0.091297,0.090870,0.090870,73449600,0.0,0.0
...,...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.0,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.0,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28229400,0.0,0.0
2026-08-17 00:00:00-04:00,306.209991,307.660004,302.940002,305.589996,38137700,0.0,0.0
2026-08-18 00:00:00-04:00,307.529999,311.489990,305.739990,309.890106,20433651,0.0,0.0

In [20]:
momentum=pd.DataFrame()
momentum["5D"]=df["Close"].pct_change(5)
momentum["20D"]=df["Close"].pct_change(20)
momentum["30D"]=df["Close"].pct_change(30)
momentum["90D"]=df["Close"].pct_change(90)

In [21]:
momentum

                                 5D       20D       30D       90D
Date
1980-12-12 00:00:00-05:00       NaN       NaN       NaN       NaN
1980-12-15 00:00:00-05:00       NaN       NaN       NaN       NaN
1980-12-16 00:00:00-05:00       NaN       NaN       NaN       NaN
1980-12-17 00:00:00-05:00       NaN       NaN       NaN       NaN
1980-12-18 00:00:00-05:00       NaN       NaN       NaN       NaN
...                             ...       ...       ...       ...
2026-08-12 00:00:00-04:00 -0.027297 -0.076303  0.045447  0.183141
2026-08-13 00:00:00-04:00 -0.022044 -0.083228  0.037853  0.181352
2026-08-14 00:00:00-04:00 -0.022775 -0.082538 -0.007893  0.208978
2026-08-17 00:00:00-04:00 -0.008662 -0.063494 -0.021770  0.182446
2026-08-18 00:00:00-04:00  0.016333 -0.053648 -0.001618  0.191766

[11512 rows x 4 columns]

In [22]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-12-12 00:00:00-05:00,0.098122,0.098549,0.098122,0.098122,469033600,0.0,0.0
1980-12-15 00:00:00-05:00,0.093430,0.093430,0.093003,0.093003,175884800,0.0,0.0
1980-12-16 00:00:00-05:00,0.086604,0.086604,0.086177,0.086177,105728000,0.0,0.0
1980-12-17 00:00:00-05:00,0.088310,0.088737,0.088310,0.088310,86441600,0.0,0.0
1980-12-18 00:00:00-05:00,0.090870,0.091297,0.090870,0.090870,73449600,0.0,0.0
...,...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.0,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.0,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28229400,0.0,0.0
2026-08-17 00:00:00-04:00,306.209991,307.660004,302.940002,305.589996,38137700,0.0,0.0
2026-08-18 00:00:00-04:00,307.529999,311.489990,305.739990,309.890106,20433651,0.0,0.0

In [23]:
rsi=pd.DataFrame()

In [24]:
rsi["Close"]=df["Close"]

In [25]:
rsi

                                Close
Date
1980-12-12 00:00:00-05:00    0.098122
1980-12-15 00:00:00-05:00    0.093003
1980-12-16 00:00:00-05:00    0.086177
1980-12-17 00:00:00-05:00    0.088310
1980-12-18 00:00:00-05:00    0.090870
...                               ...
2026-08-12 00:00:00-04:00  302.250000
2026-08-13 00:00:00-04:00  305.260010
2026-08-14 00:00:00-04:00  305.929993
2026-08-17 00:00:00-04:00  305.589996
2026-08-18 00:00:00-04:00  309.890106

[11512 rows x 1 columns]

In [26]:
rsi["change"]=rsi["Close"].diff()

In [27]:
rsi

                                Close    change
Date
1980-12-12 00:00:00-05:00    0.098122       NaN
1980-12-15 00:00:00-05:00    0.093003 -0.005119
1980-12-16 00:00:00-05:00    0.086177 -0.006826
1980-12-17 00:00:00-05:00    0.088310  0.002133
1980-12-18 00:00:00-05:00    0.090870  0.002560
...                               ...       ...
2026-08-12 00:00:00-04:00  302.250000 -2.660004
2026-08-13 00:00:00-04:00  305.260010  3.010010
2026-08-14 00:00:00-04:00  305.929993  0.669983
2026-08-17 00:00:00-04:00  305.589996 -0.339996
2026-08-18 00:00:00-04:00  309.890106  4.300110

[11512 rows x 2 columns]

In [28]:

rsi["gain"]=np.where(rsi["change"]>0,rsi["change"],0)
rsi["loss"]=np.where(rsi['change']<0,-rsi['change'],0)
rsi.loc[rsi.index[0],["gain","loss"]]=np.nan

In [29]:
rsi

                                Close    change      gain      loss
Date
1980-12-12 00:00:00-05:00    0.098122       NaN       NaN       NaN
1980-12-15 00:00:00-05:00    0.093003 -0.005119  0.000000  0.005119
1980-12-16 00:00:00-05:00    0.086177 -0.006826  0.000000  0.006826
1980-12-17 00:00:00-05:00    0.088310  0.002133  0.002133  0.000000
1980-12-18 00:00:00-05:00    0.090870  0.002560  0.002560  0.000000
...                               ...       ...       ...       ...
2026-08-12 00:00:00-04:00  302.250000 -2.660004  0.000000  2.660004
2026-08-13 00:00:00-04:00  305.260010  3.010010  3.010010  0.000000
2026-08-14 00:00:00-04:00  305.929993  0.669983  0.669983  0.000000
2026-08-17 00:00:00-04:00  305.589996 -0.339996  0.000000  0.339996
2026-08-18 00:00:00-04:00  309.890106  4.300110  4.300110  0.000000

[11512 rows x 4 columns]

In [30]:
rsi['14d_gainmean']=rsi["gain"].rolling(14).mean()
rsi['14d_lossmean']=rsi["loss"].rolling(14).mean()
rsi

,Close,change,gain,loss,14d_gainmean,14d_lossmean
Date,,,,,,
1980-12-12 00:00:00-05:00,0.098122,NaN,NaN,NaN,NaN,NaN
1980-12-15 00:00:00-05:00,0.093003,-0.005119,0.000000,0.005119,NaN,NaN
1980-12-16 00:00:00-05:00,0.086177,-0.006826,0.000000,0.006826,NaN,NaN
1980-12-17 00:00:00-05:00,0.088310,0.002133,0.002133,0.000000,NaN,NaN
1980-12-18 00:00:00-05:00,0.090870,0.002560,0.002560,0.000000,NaN,NaN
...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,302.250000,-2.660004,0.000000,2.660004,2.021822,3.388454
2026-08-13 00:00:00-04:00,305.260010,3.010010,3.010010,0.000000,1.426095,3.388454
2026-08-14 00:00:00-04:00,305.929993,0.669983,0.669983,0.000000,1.196333,3.388454
2026-08-17 00:00:00-04:00,305.589996,-0.339996,0.000000,0.339996,0.970101,3.412739
2026-08-18 00:00:00-04:00,309.890106,4.300110,4.300110,0.000000,1.277252,3.277858

In [31]:

rsi

,Close,change,gain,loss,14d_gainmean,14d_lossmean
Date,,,,,,
1980-12-12 00:00:00-05:00,0.098122,NaN,NaN,NaN,NaN,NaN
1980-12-15 00:00:00-05:00,0.093003,-0.005119,0.000000,0.005119,NaN,NaN
1980-12-16 00:00:00-05:00,0.086177,-0.006826,0.000000,0.006826,NaN,NaN
1980-12-17 00:00:00-05:00,0.088310,0.002133,0.002133,0.000000,NaN,NaN
1980-12-18 00:00:00-05:00,0.090870,0.002560,0.002560,0.000000,NaN,NaN
...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,302.250000,-2.660004,0.000000,2.660004,2.021822,3.388454
2026-08-13 00:00:00-04:00,305.260010,3.010010,3.010010,0.000000,1.426095,3.388454
2026-08-14 00:00:00-04:00,305.929993,0.669983,0.669983,0.000000,1.196333,3.388454
2026-08-17 00:00:00-04:00,305.589996,-0.339996,0.000000,0.339996,0.970101,3.412739
2026-08-18 00:00:00-04:00,309.890106,4.300110,4.300110,0.000000,1.277252,3.277858

In [32]:
rsi["wilder_averagegain"]=np.nan
rsi["wilder_averageloss"]=np.nan
first_valid = rsi["14d_gainmean"].first_valid_index()

In [33]:
rsi

,Close,change,gain,loss,14d_gainmean,14d_lossmean,wilder_averagegain,wilder_averageloss
Date,,,,,,,,
1980-12-12 00:00:00-05:00,0.098122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-12-15 00:00:00-05:00,0.093003,-0.005119,0.000000,0.005119,NaN,NaN,NaN,NaN
1980-12-16 00:00:00-05:00,0.086177,-0.006826,0.000000,0.006826,NaN,NaN,NaN,NaN
1980-12-17 00:00:00-05:00,0.088310,0.002133,0.002133,0.000000,NaN,NaN,NaN,NaN
1980-12-18 00:00:00-05:00,0.090870,0.002560,0.002560,0.000000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,302.250000,-2.660004,0.000000,2.660004,2.021822,3.388454,NaN,NaN
2026-08-13 00:00:00-04:00,305.260010,3.010010,3.010010,0.000000,1.426095,3.388454,NaN,NaN
2026-08-14 00:00:00-04:00,305.929993,0.669983,0.669983,0.000000,1.196333,3.388454,NaN,NaN
2026-08-17 00:00:00-04:00,305.589996,-0.339996,0.000000,0.339996,0.970101,3.412739,NaN,NaN
2026-08-18 00:00:00-04:00,309.890106,4.300110,4.300110,0.000000,1.277252,3.277858,NaN,NaN

In [34]:
rsi.columns.get_loc("wilder_averagegain")

6

In [35]:
first_valid=rsi["14d_gainmean"].first_valid_index()

In [36]:
rsi.loc[rsi["14d_gainmean"].first_valid_index(),"wilder_averagegain"]=rsi.loc[rsi["14d_gainmean"].first_valid_index(),"14d_gainmean"]
rsi.loc[rsi["14d_lossmean"].first_valid_index(),"wilder_averagegain"]=rsi.loc[rsi["14d_lossmean"].first_valid_index(),"14d_lossmean"]

In [37]:
rsi.loc[rsi["14d_gainmean"].first_valid_index()]

Close                 0.115188
change               -0.002560
gain                  0.000000
loss                  0.002560
14d_gainmean          0.002712
14d_lossmean          0.001493
wilder_averagegain    0.001493
wilder_averageloss         NaN
Name: 1981-01-05 00:00:00-05:00, dtype: float64

In [38]:
rsi["wilder_averagegain"].first_valid_index()

Timestamp('1981-01-05 00:00:00-0500', tz='America/New_York')

In [39]:
first_valid_index=rsi.index.get_loc(first_valid)
first_valid_index
series=rsi["gain"].copy()

In [40]:
# rsi.iloc[(rsi.index.get_loc(first_valid)+1):,rsi.columns.get_loc("wilder_averagegain")]=rsi.iloc[(rsi.index.get_loc(first_valid)+1):,rsi.columns.get_loc("gain")].ewm(alpha=1/14,adjust=False).mean()

In [41]:
rsi

,Close,change,gain,loss,14d_gainmean,14d_lossmean,wilder_averagegain,wilder_averageloss
Date,,,,,,,,
1980-12-12 00:00:00-05:00,0.098122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-12-15 00:00:00-05:00,0.093003,-0.005119,0.000000,0.005119,NaN,NaN,NaN,NaN
1980-12-16 00:00:00-05:00,0.086177,-0.006826,0.000000,0.006826,NaN,NaN,NaN,NaN
1980-12-17 00:00:00-05:00,0.088310,0.002133,0.002133,0.000000,NaN,NaN,NaN,NaN
1980-12-18 00:00:00-05:00,0.090870,0.002560,0.002560,0.000000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,302.250000,-2.660004,0.000000,2.660004,2.021822,3.388454,NaN,NaN
2026-08-13 00:00:00-04:00,305.260010,3.010010,3.010010,0.000000,1.426095,3.388454,NaN,NaN
2026-08-14 00:00:00-04:00,305.929993,0.669983,0.669983,0.000000,1.196333,3.388454,NaN,NaN
2026-08-17 00:00:00-04:00,305.589996,-0.339996,0.000000,0.339996,0.970101,3.412739,NaN,NaN
2026-08-18 00:00:00-04:00,309.890106,4.300110,4.300110,0.000000,1.277252,3.277858,NaN,NaN

In [42]:
series

Date
1980-12-12 00:00:00-05:00         NaN
1980-12-15 00:00:00-05:00    0.000000
1980-12-16 00:00:00-05:00    0.000000
1980-12-17 00:00:00-05:00    0.002133
1980-12-18 00:00:00-05:00    0.002560
                               ...
2026-08-12 00:00:00-04:00    0.000000
2026-08-13 00:00:00-04:00    3.010010
2026-08-14 00:00:00-04:00    0.669983
2026-08-17 00:00:00-04:00    0.000000
2026-08-18 00:00:00-04:00    4.300110
Name: gain, Length: 11512, dtype: float64

In [43]:
rsi

,Close,change,gain,loss,14d_gainmean,14d_lossmean,wilder_averagegain,wilder_averageloss
Date,,,,,,,,
1980-12-12 00:00:00-05:00,0.098122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-12-15 00:00:00-05:00,0.093003,-0.005119,0.000000,0.005119,NaN,NaN,NaN,NaN
1980-12-16 00:00:00-05:00,0.086177,-0.006826,0.000000,0.006826,NaN,NaN,NaN,NaN
1980-12-17 00:00:00-05:00,0.088310,0.002133,0.002133,0.000000,NaN,NaN,NaN,NaN
1980-12-18 00:00:00-05:00,0.090870,0.002560,0.002560,0.000000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,302.250000,-2.660004,0.000000,2.660004,2.021822,3.388454,NaN,NaN
2026-08-13 00:00:00-04:00,305.260010,3.010010,3.010010,0.000000,1.426095,3.388454,NaN,NaN
2026-08-14 00:00:00-04:00,305.929993,0.669983,0.669983,0.000000,1.196333,3.388454,NaN,NaN
2026-08-17 00:00:00-04:00,305.589996,-0.339996,0.000000,0.339996,0.970101,3.412739,NaN,NaN
2026-08-18 00:00:00-04:00,309.890106,4.300110,4.300110,0.000000,1.277252,3.277858,NaN,NaN

In [44]:
rsi.iloc[first_valid_index,rsi.columns.get_loc("14d_gainmean")]

np.float64(0.0027120629591601236)

In [45]:
series[first_valid]=rsi.iloc[first_valid_index,rsi.columns.get_loc("14d_gainmean")]
series

Date
1980-12-12 00:00:00-05:00         NaN
1980-12-15 00:00:00-05:00    0.000000
1980-12-16 00:00:00-05:00    0.000000
1980-12-17 00:00:00-05:00    0.002133
1980-12-18 00:00:00-05:00    0.002560
                               ...
2026-08-12 00:00:00-04:00    0.000000
2026-08-13 00:00:00-04:00    3.010010
2026-08-14 00:00:00-04:00    0.669983
2026-08-17 00:00:00-04:00    0.000000
2026-08-18 00:00:00-04:00    4.300110
Name: gain, Length: 11512, dtype: float64

In [46]:
series.iloc[14]

np.float64(0.0027120629591601236)

In [47]:
rsi

,Close,change,gain,loss,14d_gainmean,14d_lossmean,wilder_averagegain,wilder_averageloss
Date,,,,,,,,
1980-12-12 00:00:00-05:00,0.098122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-12-15 00:00:00-05:00,0.093003,-0.005119,0.000000,0.005119,NaN,NaN,NaN,NaN
1980-12-16 00:00:00-05:00,0.086177,-0.006826,0.000000,0.006826,NaN,NaN,NaN,NaN
1980-12-17 00:00:00-05:00,0.088310,0.002133,0.002133,0.000000,NaN,NaN,NaN,NaN
1980-12-18 00:00:00-05:00,0.090870,0.002560,0.002560,0.000000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,302.250000,-2.660004,0.000000,2.660004,2.021822,3.388454,NaN,NaN
2026-08-13 00:00:00-04:00,305.260010,3.010010,3.010010,0.000000,1.426095,3.388454,NaN,NaN
2026-08-14 00:00:00-04:00,305.929993,0.669983,0.669983,0.000000,1.196333,3.388454,NaN,NaN
2026-08-17 00:00:00-04:00,305.589996,-0.339996,0.000000,0.339996,0.970101,3.412739,NaN,NaN
2026-08-18 00:00:00-04:00,309.890106,4.300110,4.300110,0.000000,1.277252,3.277858,NaN,NaN

In [48]:
rsi["wilder_averagegain"]=np.nan
rsi["wilder_averageloss"]=np.nan

In [49]:
rsi

,Close,change,gain,loss,14d_gainmean,14d_lossmean,wilder_averagegain,wilder_averageloss
Date,,,,,,,,
1980-12-12 00:00:00-05:00,0.098122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-12-15 00:00:00-05:00,0.093003,-0.005119,0.000000,0.005119,NaN,NaN,NaN,NaN
1980-12-16 00:00:00-05:00,0.086177,-0.006826,0.000000,0.006826,NaN,NaN,NaN,NaN
1980-12-17 00:00:00-05:00,0.088310,0.002133,0.002133,0.000000,NaN,NaN,NaN,NaN
1980-12-18 00:00:00-05:00,0.090870,0.002560,0.002560,0.000000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,302.250000,-2.660004,0.000000,2.660004,2.021822,3.388454,NaN,NaN
2026-08-13 00:00:00-04:00,305.260010,3.010010,3.010010,0.000000,1.426095,3.388454,NaN,NaN
2026-08-14 00:00:00-04:00,305.929993,0.669983,0.669983,0.000000,1.196333,3.388454,NaN,NaN
2026-08-17 00:00:00-04:00,305.589996,-0.339996,0.000000,0.339996,0.970101,3.412739,NaN,NaN
2026-08-18 00:00:00-04:00,309.890106,4.300110,4.300110,0.000000,1.277252,3.277858,NaN,NaN

In [50]:
rsi.insert(6,"temp_gain",rsi["gain"].copy())

In [51]:
rsi["temp_gain"]=rsi["gain"].copy()
rsi.loc[first_valid,"temp_gain"]=rsi.loc[first_valid,"14d_gainmean"]
rsi.loc[first_valid:,"wilder_averagegain"]=rsi.loc[first_valid:,"temp_gain"].ewm(alpha=1/14,adjust=False).mean()

In [52]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-12-12 00:00:00-05:00,0.098122,0.098549,0.098122,0.098122,469033600,0.0,0.0
1980-12-15 00:00:00-05:00,0.093430,0.093430,0.093003,0.093003,175884800,0.0,0.0
1980-12-16 00:00:00-05:00,0.086604,0.086604,0.086177,0.086177,105728000,0.0,0.0
1980-12-17 00:00:00-05:00,0.088310,0.088737,0.088310,0.088310,86441600,0.0,0.0
1980-12-18 00:00:00-05:00,0.090870,0.091297,0.090870,0.090870,73449600,0.0,0.0
...,...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,305.100006,305.660004,300.570007,302.250000,41657800,0.0,0.0
2026-08-13 00:00:00-04:00,304.209991,306.000000,302.049988,305.260010,40349300,0.0,0.0
2026-08-14 00:00:00-04:00,306.000000,307.489990,304.299988,305.929993,28229400,0.0,0.0
2026-08-17 00:00:00-04:00,306.209991,307.660004,302.940002,305.589996,38137700,0.0,0.0
2026-08-18 00:00:00-04:00,307.529999,311.489990,305.739990,309.890106,20433651,0.0,0.0

In [53]:
rsi

,Close,change,gain,loss,14d_gainmean,14d_lossmean,temp_gain,wilder_averagegain,wilder_averageloss
Date,,,,,,,,,
1980-12-12 00:00:00-05:00,0.098122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-12-15 00:00:00-05:00,0.093003,-0.005119,0.000000,0.005119,NaN,NaN,0.000000,NaN,NaN
1980-12-16 00:00:00-05:00,0.086177,-0.006826,0.000000,0.006826,NaN,NaN,0.000000,NaN,NaN
1980-12-17 00:00:00-05:00,0.088310,0.002133,0.002133,0.000000,NaN,NaN,0.002133,NaN,NaN
1980-12-18 00:00:00-05:00,0.090870,0.002560,0.002560,0.000000,NaN,NaN,0.002560,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,302.250000,-2.660004,0.000000,2.660004,2.021822,3.388454,0.000000,1.880402,NaN
2026-08-13 00:00:00-04:00,305.260010,3.010010,3.010010,0.000000,1.426095,3.388454,3.010010,1.961088,NaN
2026-08-14 00:00:00-04:00,305.929993,0.669983,0.669983,0.000000,1.196333,3.388454,0.669983,1.868866,NaN
2026-08-17 00:00:00-04:00,305.589996,-0.339996,0.000000,0.339996,0.970101,3.412739,0.000000,1.735376,NaN
2026-08-18 00:00:00-04:00,309.890106,4.300110,4.300110,0.000000,1.277252,3.277858,4.300110,1.918571,NaN

In [54]:
print("first valid sma=",rsi.loc[first_valid,"14d_gainmean"])
print("first value with last line of code=",rsi.loc[first_valid,"wilder_averagegain"])

first valid sma= 0.0027120629591601236
first value with last line of code= 0.0027120629591601236

In [55]:
print("first value without last line of code=",rsi.loc[first_valid,"wilder_averagegain"])

first value without last line of code= 0.0027120629591601236

In [56]:
rsi=pd.DataFrame()

In [57]:
def calc_rsi(df):
    rsi=pd.DataFrame()
    rsi["Close"]=df["Close"]
    rsi["change"]=rsi["Close"].diff()
    rsi["gain"]=np.where(rsi["change"]>0,rsi["change"],0)
    rsi["loss"]=np.where(rsi['change']<0,-rsi['change'],0)
    rsi.loc[rsi.index[0],["gain","loss"]]=np.nan#so np.where doesnt make a 0 entry at 0th row in gain and loss instead replaced with nan
    rsi['14d_gainmean']=rsi["gain"].rolling(14).mean()
    rsi['14d_lossmean']=rsi["loss"].rolling(14).mean()
    rsi["wilder_averagegain"]=np.nan
    rsi["wilder_averageloss"]=np.nan
    first_valid = rsi["14d_gainmean"].first_valid_index()
    #creating columns for seeding first valid sma and calculation ewm
    rsi["temp_gain"]=rsi["gain"].copy()
    rsi["temp_loss"]=rsi["loss"].copy()
    #seeding first valid sma
    rsi.loc[first_valid,"temp_gain"]=rsi.loc[first_valid,"14d_gainmean"]
    rsi.loc[first_valid,"temp_loss"]=rsi.loc[first_valid,"14d_lossmean"]
    #calculating ewm for rows[first_valid_position:] and putting them inside wilder average gain and wilder average loss
    rsi.loc[first_valid:,"wilder_averagegain"]=rsi.loc[first_valid:,"temp_gain"].ewm(alpha=1/14,adjust=False).mean()
    rsi.loc[first_valid:,"wilder_averageloss"]=rsi.loc[first_valid:,"temp_loss"].ewm(alpha=1/14,adjust=False).mean()
    rsi["RS"]=rsi["wilder_averagegain"]/rsi["wilder_averageloss"]
    rsi["RSI"]=(100-100/(1+rsi["RS"]))
    return(rsi[["RSI"]])##only returning RSI column as a dataframe
calc_rsi(df)

                                 RSI
Date
1980-12-12 00:00:00-05:00        NaN
1980-12-15 00:00:00-05:00        NaN
1980-12-16 00:00:00-05:00        NaN
1980-12-17 00:00:00-05:00        NaN
1980-12-18 00:00:00-05:00        NaN
...                              ...
2026-08-12 00:00:00-04:00  40.356741
2026-08-13 00:00:00-04:00  43.180250
2026-08-14 00:00:00-04:00  43.817790
2026-08-17 00:00:00-04:00  43.550736
2026-08-18 00:00:00-04:00  47.877502

[11512 rows x 1 columns]

VOLUME METRICS

#voluma sma20

In [109]:
volume_metrics=pd.DataFrame()
volume_metrics["volume"]=df["Volume"].copy()

In [110]:
volume_metrics

                              volume
Date
1980-12-12 00:00:00-05:00  469033600
1980-12-15 00:00:00-05:00  175884800
1980-12-16 00:00:00-05:00  105728000
1980-12-17 00:00:00-05:00   86441600
1980-12-18 00:00:00-05:00   73449600
...                              ...
2026-08-12 00:00:00-04:00   41657800
2026-08-13 00:00:00-04:00   40349300
2026-08-14 00:00:00-04:00   28229400
2026-08-17 00:00:00-04:00   38137700
2026-08-18 00:00:00-04:00   20433651

[11512 rows x 1 columns]

In [111]:
volume_metrics["daily_vol_change"]=volume_metrics["volume"].diff()
volume_metrics["daily_%_change"]=volume_metrics["volume"].pct_change()
volume_metrics["avg_volume_20d"]=volume_metrics["volume"].rolling(20).mean()
volume_metrics["RVOL"]=volume_metrics["volume"]/volume_metrics["avg_volume_20d"]
volume_metrics["OBV"]=np.nan
volume_metrics["daily_change"]=df["Close"].diff()
volume_metrics["signed_volume"]=np.nan

In [112]:
volume_metrics

,volume,daily_vol_change,daily_%_change,avg_volume_20d,RVOL,OBV,daily_change,signed_volume
Date,,,,,,,,
1980-12-12 00:00:00-05:00,469033600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-12-15 00:00:00-05:00,175884800,-293148800.0,-0.625006,NaN,NaN,NaN,-0.005119,NaN
1980-12-16 00:00:00-05:00,105728000,-70156800.0,-0.398879,NaN,NaN,NaN,-0.006826,NaN
1980-12-17 00:00:00-05:00,86441600,-19286400.0,-0.182415,NaN,NaN,NaN,0.002133,NaN
1980-12-18 00:00:00-05:00,73449600,-12992000.0,-0.150298,NaN,NaN,NaN,0.002560,NaN
...,...,...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,41657800,4181100.0,0.111565,55507380.00,0.750491,NaN,-2.660004,NaN
2026-08-13 00:00:00-04:00,40349300,-1308500.0,-0.031411,54376315.00,0.742038,NaN,3.010010,NaN
2026-08-14 00:00:00-04:00,28229400,-12119900.0,-0.300374,52617430.00,0.536503,NaN,0.669983,NaN
2026-08-17 00:00:00-04:00,38137700,9908300.0,0.350992,51850915.00,0.735526,NaN,-0.339996,NaN
2026-08-18 00:00:00-04:00,20433651,-17704049.0,-0.464214,50805652.55,0.402192,NaN,4.300110,NaN

In [62]:
# volume_metrics["signed_volume"]=np.where((volume_metrics["daily_change"]>0),volume_metrics["volume"],np.where(volume_metrics["daily_change"]==0,0,-volume_metrics["volume"]))

In [113]:
volume_metrics["signed_volume"]=np.select(
    [volume_metrics["daily_change"]>0,
     volume_metrics["daily_change"]<0,
     volume_metrics["daily_change"]==0,
     volume_metrics["daily_change"].isna()
     ],
    [
        volume_metrics["volume"],-volume_metrics["volume"],0,volume_metrics["volume"]
    ],
    default=np.nan
)

In [114]:
volume_metrics

,volume,daily_vol_change,daily_%_change,avg_volume_20d,RVOL,OBV,daily_change,signed_volume
Date,,,,,,,,
1980-12-12 00:00:00-05:00,469033600,NaN,NaN,NaN,NaN,NaN,NaN,469033600.0
1980-12-15 00:00:00-05:00,175884800,-293148800.0,-0.625006,NaN,NaN,NaN,-0.005119,-175884800.0
1980-12-16 00:00:00-05:00,105728000,-70156800.0,-0.398879,NaN,NaN,NaN,-0.006826,-105728000.0
1980-12-17 00:00:00-05:00,86441600,-19286400.0,-0.182415,NaN,NaN,NaN,0.002133,86441600.0
1980-12-18 00:00:00-05:00,73449600,-12992000.0,-0.150298,NaN,NaN,NaN,0.002560,73449600.0
...,...,...,...,...,...,...,...,...
2026-08-12 00:00:00-04:00,41657800,4181100.0,0.111565,55507380.00,0.750491,NaN,-2.660004,-41657800.0
2026-08-13 00:00:00-04:00,40349300,-1308500.0,-0.031411,54376315.00,0.742038,NaN,3.010010,40349300.0
2026-08-14 00:00:00-04:00,28229400,-12119900.0,-0.300374,52617430.00,0.536503,NaN,0.669983,28229400.0
2026-08-17 00:00:00-04:00,38137700,9908300.0,0.350992,51850915.00,0.735526,NaN,-0.339996,-38137700.0
2026-08-18 00:00:00-04:00,20433651,-17704049.0,-0.464214,50805652.55,0.402192,NaN,4.300110,20433651.0

In [65]:
volume_metrics["OBV"]=volume_metrics["signed_volume"].cumsum()

In [66]:
macd_dataframe=pd.DataFrame()

In [67]:
#CALCULATING MACD
macd_dataframe=pd.DataFrame()
macd_dataframe["EMA12"]=df["Close"].ewm(span=12,adjust=False).mean()
macd_dataframe["EMA26"]=df["Close"].ewm(span=26,adjust=False).mean()
macd_dataframe["MACD"]=macd_dataframe["EMA12"]-macd_dataframe["EMA26"]
macd_dataframe["MACD_SIGNAL"]=macd_dataframe["MACD"].ewm(span=9,adjust=False).mean()
macd_dataframe["MACD_HISTOGRAM"]=macd_dataframe["MACD"]-macd_dataframe["MACD_SIGNAL"]

In [68]:
macd_dataframe

,EMA12,EMA26,MACD,MACD_SIGNAL,MACD_HISTOGRAM
Date,,,,,
1980-12-12 00:00:00-05:00,0.098122,0.098122,0.000000,0.000000,0.000000
1980-12-15 00:00:00-05:00,0.097335,0.097743,-0.000408,-0.000082,-0.000327
1980-12-16 00:00:00-05:00,0.095618,0.096886,-0.001268,-0.000319,-0.000949
1980-12-17 00:00:00-05:00,0.094494,0.096251,-0.001757,-0.000607,-0.001151
1980-12-18 00:00:00-05:00,0.093936,0.095853,-0.001916,-0.000869,-0.001048
...,...,...,...,...,...
2026-08-12 00:00:00-04:00,312.360442,314.042857,-1.682414,1.627580,-3.309995
2026-08-13 00:00:00-04:00,311.268068,313.392275,-2.124207,0.877223,-3.001430
2026-08-14 00:00:00-04:00,310.446826,312.839514,-2.392688,0.223241,-2.615929
2026-08-17 00:00:00-04:00,309.699621,312.302512,-2.602891,-0.341986,-2.260905
2026-08-18 00:00:00-04:00,309.728927,312.123816,-2.394889,-0.752566,-1.642323

In [69]:
#calculating bollinger bands
bollinger_bands=pd.DataFrame()
bollinger_bands["MIDDLE_BAND"]=df["Close"].rolling(20).mean()
bollinger_bands["std_20"]=df["Close"].rolling(20).std()
bollinger_bands["UPPER_BAND"]=bollinger_bands["MIDDLE_BAND"]+2*bollinger_bands["std_20"]
bollinger_bands["LOWER_BAND"]=bollinger_bands["MIDDLE_BAND"]-2*bollinger_bands["std_20"]
bollinger_bands

                           MIDDLE_BAND     std_20  UPPER_BAND  LOWER_BAND
Date
1980-12-12 00:00:00-05:00          NaN        NaN         NaN         NaN
1980-12-15 00:00:00-05:00          NaN        NaN         NaN         NaN
1980-12-16 00:00:00-05:00          NaN        NaN         NaN         NaN
1980-12-17 00:00:00-05:00          NaN        NaN         NaN         NaN
1980-12-18 00:00:00-05:00          NaN        NaN         NaN         NaN
...                                ...        ...         ...         ...
2026-08-12 00:00:00-04:00   320.981648  12.955941  346.893530  295.069767
2026-08-13 00:00:00-04:00   319.596007  13.087263  345.770534  293.421480
2026-08-14 00:00:00-04:00   318.219887  13.000282  344.220450  292.219323
2026-08-17 00:00:00-04:00   317.183958  13.146470  343.476898  290.891019
2026-08-18 00:00:00-04:00   316.305585  13.010089  342.325763  290.285407

[11512 rows x 4 columns]

In [101]:
atr=pd.DataFrame()
atr["high-low"]=df["High"]-df["Low"]
atr["abs_high-prevclose"]=(df["High"]-df["Close"].shift(1)).abs()
atr["abd_low-prevclose"]=(df["Low"]-df["Close"].shift(1)).abs()
atr["tr"]=atr.max(axis=1)
atr["atr"]=np.nan

In [102]:
atr

,high-low,abs_high-prevclose,abd_low-prevclose,tr,atr
Date,,,,,
1980-12-12 00:00:00-05:00,0.000427,NaN,NaN,0.000427,NaN
1980-12-15 00:00:00-05:00,0.000427,0.004692,0.005119,0.005119,NaN
1980-12-16 00:00:00-05:00,0.000427,0.006400,0.006826,0.006826,NaN
1980-12-17 00:00:00-05:00,0.000427,0.002560,0.002133,0.002560,NaN
1980-12-18 00:00:00-05:00,0.000427,0.002987,0.002560,0.002987,NaN
...,...,...,...,...,...
2026-08-12 00:00:00-04:00,5.089996,0.750000,4.339996,5.089996,NaN
2026-08-13 00:00:00-04:00,3.950012,3.750000,0.200012,3.950012,NaN
2026-08-14 00:00:00-04:00,3.190002,2.229980,0.960022,3.190002,NaN
2026-08-17 00:00:00-04:00,4.720001,1.730011,2.989990,4.720001,NaN
2026-08-18 00:00:00-04:00,5.750000,5.899994,0.149994,5.899994,NaN

In [103]:
initial_atr=atr["tr"].iloc[:14].mean()
initial_atr

np.float64(0.00435759019180336)

In [104]:
atr

,high-low,abs_high-prevclose,abd_low-prevclose,tr,atr
Date,,,,,
1980-12-12 00:00:00-05:00,0.000427,NaN,NaN,0.000427,NaN
1980-12-15 00:00:00-05:00,0.000427,0.004692,0.005119,0.005119,NaN
1980-12-16 00:00:00-05:00,0.000427,0.006400,0.006826,0.006826,NaN
1980-12-17 00:00:00-05:00,0.000427,0.002560,0.002133,0.002560,NaN
1980-12-18 00:00:00-05:00,0.000427,0.002987,0.002560,0.002987,NaN
...,...,...,...,...,...
2026-08-12 00:00:00-04:00,5.089996,0.750000,4.339996,5.089996,NaN
2026-08-13 00:00:00-04:00,3.950012,3.750000,0.200012,3.950012,NaN
2026-08-14 00:00:00-04:00,3.190002,2.229980,0.960022,3.190002,NaN
2026-08-17 00:00:00-04:00,4.720001,1.730011,2.989990,4.720001,NaN
2026-08-18 00:00:00-04:00,5.750000,5.899994,0.149994,5.899994,NaN

In [107]:
atr.iloc[13:,atr.columns.get_loc("atr")]=(pd.concat([pd.Series([initial_atr]),atr["tr"].iloc[14:]]).ewm(alpha=1/14,adjust=False).mean().values)

In [108]:
atr

,high-low,abs_high-prevclose,abd_low-prevclose,tr,atr
Date,,,,,
1980-12-12 00:00:00-05:00,0.000427,NaN,NaN,0.000427,NaN
1980-12-15 00:00:00-05:00,0.000427,0.004692,0.005119,0.005119,NaN
1980-12-16 00:00:00-05:00,0.000427,0.006400,0.006826,0.006826,NaN
1980-12-17 00:00:00-05:00,0.000427,0.002560,0.002133,0.002560,NaN
1980-12-18 00:00:00-05:00,0.000427,0.002987,0.002560,0.002987,NaN
...,...,...,...,...,...
2026-08-12 00:00:00-04:00,5.089996,0.750000,4.339996,5.089996,8.525791
2026-08-13 00:00:00-04:00,3.950012,3.750000,0.200012,3.950012,8.198950
2026-08-14 00:00:00-04:00,3.190002,2.229980,0.960022,3.190002,7.841168
2026-08-17 00:00:00-04:00,4.720001,1.730011,2.989990,4.720001,7.618227
2026-08-18 00:00:00-04:00,5.750000,5.899994,0.149994,5.899994,7.495496